#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 86
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_LF = 3,
  anon_sym_SEMI = 4,
  sym_arg_spliter = 5,
  sym_leading_key = 6,
  anon_sym_PLUS_EQ = 7,
  anon_sym_EQ = 8,
  anon_sym_DASH_EQ = 9,
  anon_sym_PLUS = 10,
  anon_sym_DASH = 11,
  anon_sym_TILDE = 12,
  anon_sym_DASH_GT = 13,
  anon_sym_DOT = 14,
  anon_sym_AT = 15,
  anon_sym_LPAREN = 16,
  anon_sym_RPAREN = 17,
  anon_sym_SQUOTE = 18,
  aux_sym_string_token1 = 19,
  anon_sym_DQUOTE = 20,
  aux_sym_string_token2 = 21,
  anon_sym_LBRACK = 22,
  anon_sym_RBRACK = 23,
  sym_identifier = 24,
  sym_escape_sequence = 25,
  sym_number = 26,
  sym_line_comment = 27,
  sym_block_comment = 28,
  sym_source_file = 29,
  sym_block = 30,
  sym_command = 31,
  sym__command_unit = 32,
  sym_operators = 33,
  sym_unit = 34,
  sym_decorate = 35,
  sym__unit = 36,
  sym_func = 37,
  sym_arg_block = 38,
  sym_string = 39,
  sym_list = 40,
  sym__args = 41,
  sym_comment = 42,
  aux_sym_source_file_repeat1 = 43,
  aux_sym_command_repeat1 = 44,
  aux_sym_unit_repeat1 = 45,
  aux_sym_string_repeat1 = 46,
  aux_sym_string_repeat2 = 47,
  aux_sym__args_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LF] = "\n",
  [anon_sym_SEMI] = ";",
  [sym_arg_spliter] = "arg_spliter",
  [sym_leading_key] = "leading_key",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_EQ] = "=",
  [anon_sym_DASH_EQ] = "-=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_TILDE] = "~",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_DOT] = ".",
  [anon_sym_AT] = "@",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_identifier] = "identifier",
  [sym_escape_sequence] = "escape_sequence",
  [sym_number] = "number",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym_block] = "block",
  [sym_command] = "command",
  [sym__command_unit] = "_command_unit",
  [sym_operators] = "operators",
  [sym_unit] = "unit",
  [sym_decorate] = "decorate",
  [sym__unit] = "_unit",
  [sym_func] = "func",
  [sym_arg_block] = "arg_block",
  [sym_string] = "string",
  [sym_list] = "list",
  [sym__args] = "_args",
  [sym_comment] = "comment",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_command_repeat1] = "command_repeat1",
  [aux_sym_unit_repeat1] = "unit_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
  [aux_sym__args_repeat1] = "_args_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_arg_spliter] = sym_arg_spliter,
  [sym_leading_key] = sym_leading_key,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DASH_EQ] = anon_sym_DASH_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_identifier] = sym_identifier,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_number] = sym_number,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym_block] = sym_block,
  [sym_command] = sym_command,
  [sym__command_unit] = sym__command_unit,
  [sym_operators] = sym_operators,
  [sym_unit] = sym_unit,
  [sym_decorate] = sym_decorate,
  [sym__unit] = sym__unit,
  [sym_func] = sym_func,
  [sym_arg_block] = sym_arg_block,
  [sym_string] = sym_string,
  [sym_list] = sym_list,
  [sym__args] = sym__args,
  [sym_comment] = sym_comment,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_command_repeat1] = aux_sym_command_repeat1,
  [aux_sym_unit_repeat1] = aux_sym_unit_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
  [aux_sym__args_repeat1] = aux_sym__args_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_arg_spliter] = {
    .visible = true,
    .named = true,
  },
  [sym_leading_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym__command_unit] = {
    .visible = false,
    .named = true,
  },
  [sym_operators] = {
    .visible = true,
    .named = true,
  },
  [sym_unit] = {
    .visible = true,
    .named = true,
  },
  [sym_decorate] = {
    .visible = true,
    .named = true,
  },
  [sym__unit] = {
    .visible = false,
    .named = true,
  },
  [sym_func] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_block] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__args] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unit_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__args_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 11,
  [36] = 36,
  [37] = 36,
  [38] = 12,
  [39] = 14,
  [40] = 13,
  [41] = 41,
  [42] = 41,
  [43] = 20,
  [44] = 15,
  [45] = 16,
  [46] = 21,
  [47] = 19,
  [48] = 18,
  [49] = 17,
  [50] = 50,
  [51] = 28,
  [52] = 27,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 55,
  [57] = 57,
  [58] = 58,
  [59] = 57,
  [60] = 58,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 63,
  [65] = 65,
  [66] = 66,
  [67] = 65,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 26,
  [72] = 23,
  [73] = 73,
  [74] = 24,
  [75] = 29,
  [76] = 25,
  [77] = 77,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 81,
  [83] = 79,
  [84] = 78,
  [85] = 85,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      if (lookahead == '"') ADVANCE(48);
      if (lookahead == '$') ADVANCE(29);
      if (lookahead == '\'') ADVANCE(41);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == ')') ADVANCE(40);
      if (lookahead == '+') ADVANCE(33);
      if (lookahead == ',') ADVANCE(28);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == '.') ADVANCE(37);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '0') ADVANCE(62);
      if (lookahead == ';') ADVANCE(27);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == '[') ADVANCE(55);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == ']') ADVANCE(56);
      if (lookahead == '{') ADVANCE(24);
      if (lookahead == '}') ADVANCE(25);
      if (lookahead == '~') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(22)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(63);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '"') ADVANCE(48);
      if (lookahead == '\'') ADVANCE(41);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == '+') ADVANCE(33);
      if (lookahead == ',') ADVANCE(28);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == '.') ADVANCE(37);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '0') ADVANCE(62);
      if (lookahead == ';') ADVANCE(27);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == '[') ADVANCE(55);
      if (lookahead == '{') ADVANCE(24);
      if (lookahead == '~') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(63);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(48);
      if (lookahead == '$') ADVANCE(29);
      if (lookahead == '/') ADVANCE(50);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '^') ADVANCE(54);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(41);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0) ADVANCE(47);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(71);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(72);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(8);
      if (lookahead == 'x') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(60);
      if (lookahead != 0) ADVANCE(58);
      END_STATE();
    case 8:
      if (lookahead == '{') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == '}') ADVANCE(58);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 11:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(64);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(65);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(58);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(66);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      END_STATE();
    case 22:
      if (eof) ADVANCE(23);
      if (lookahead == '"') ADVANCE(48);
      if (lookahead == '$') ADVANCE(29);
      if (lookahead == '\'') ADVANCE(41);
      if (lookahead == '(') ADVANCE(39);
      if (lookahead == ')') ADVANCE(40);
      if (lookahead == '+') ADVANCE(33);
      if (lookahead == ',') ADVANCE(28);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == '.') ADVANCE(37);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '0') ADVANCE(62);
      if (lookahead == ';') ADVANCE(27);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '@') ADVANCE(38);
      if (lookahead == '[') ADVANCE(55);
      if (lookahead == ']') ADVANCE(56);
      if (lookahead == '{') ADVANCE(24);
      if (lookahead == '}') ADVANCE(25);
      if (lookahead == '~') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(22)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(63);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_arg_spliter);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_leading_key);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DASH_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '=') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '>') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(42);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(45);
      if (lookahead == '/') ADVANCE(42);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(47);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead == '/') ADVANCE(47);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(45);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(44);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(43);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(47);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\n') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(52);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(54);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(51);
      if (lookahead == '/') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(52);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(51);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '/') ADVANCE(50);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(58);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(59);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_number);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == '0') ADVANCE(67);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(11);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(10);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(12);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(18);
      if (lookahead == '_') ADVANCE(16);
      if (lookahead == 'n') ADVANCE(61);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(70);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(10);
      if (lookahead == '_') ADVANCE(13);
      if (lookahead == 'n') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(11);
      if (lookahead == 'n') ADVANCE(61);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(12);
      if (lookahead == 'n') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(16);
      if (lookahead == 'n') ADVANCE(61);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(68);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(10);
      if (lookahead == '_') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 1},
  [12] = {.lex_state = 1},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 1},
  [15] = {.lex_state = 1},
  [16] = {.lex_state = 1},
  [17] = {.lex_state = 1},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 2},
  [58] = {.lex_state = 2},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 3},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 3},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 2},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {(TSStateId)(-1)},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [sym_comment] = STATE(0),
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_arg_spliter] = ACTIONS(1),
    [sym_leading_key] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DASH_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
  },
  [1] = {
    [sym_source_file] = STATE(80),
    [sym_block] = STATE(25),
    [sym_command] = STATE(30),
    [sym__command_unit] = STATE(22),
    [sym_operators] = STATE(25),
    [sym_unit] = STATE(25),
    [sym_decorate] = STATE(25),
    [sym__unit] = STATE(12),
    [sym_func] = STATE(15),
    [sym_string] = STATE(25),
    [sym_list] = STATE(25),
    [sym_comment] = STATE(1),
    [aux_sym_source_file_repeat1] = STATE(7),
    [aux_sym_command_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(7),
    [sym_arg_spliter] = ACTIONS(5),
    [anon_sym_PLUS_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_DASH_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(5),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
  },
  [2] = {
    [sym_block] = STATE(25),
    [sym_command] = STATE(30),
    [sym__command_unit] = STATE(22),
    [sym_operators] = STATE(25),
    [sym_unit] = STATE(25),
    [sym_decorate] = STATE(25),
    [sym__unit] = STATE(12),
    [sym_func] = STATE(15),
    [sym_string] = STATE(25),
    [sym_list] = STATE(25),
    [sym_comment] = STATE(2),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_command_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_RBRACE] = ACTIONS(23),
    [sym_arg_spliter] = ACTIONS(25),
    [anon_sym_PLUS_EQ] = ACTIONS(28),
    [anon_sym_EQ] = ACTIONS(28),
    [anon_sym_DASH_EQ] = ACTIONS(28),
    [anon_sym_PLUS] = ACTIONS(31),
    [anon_sym_DASH] = ACTIONS(31),
    [anon_sym_TILDE] = ACTIONS(28),
    [anon_sym_DASH_GT] = ACTIONS(28),
    [anon_sym_AT] = ACTIONS(34),
    [anon_sym_SQUOTE] = ACTIONS(37),
    [anon_sym_DQUOTE] = ACTIONS(40),
    [anon_sym_LBRACK] = ACTIONS(43),
    [sym_identifier] = ACTIONS(46),
    [sym_number] = ACTIONS(25),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
  },
  [3] = {
    [sym_block] = STATE(25),
    [sym_command] = STATE(30),
    [sym__command_unit] = STATE(22),
    [sym_operators] = STATE(25),
    [sym_unit] = STATE(25),
    [sym_decorate] = STATE(25),
    [sym__unit] = STATE(12),
    [sym_func] = STATE(15),
    [sym_string] = STATE(25),
    [sym_list] = STATE(25),
    [sym_comment] = STATE(3),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_command_repeat1] = STATE(8),
    [anon_sym_RBRACE] = ACTIONS(49),
    [sym_arg_spliter] = ACTIONS(5),
    [anon_sym_PLUS_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_DASH_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(5),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
  },
  [4] = {
    [sym_block] = STATE(25),
    [sym_command] = STATE(30),
    [sym__command_unit] = STATE(22),
    [sym_operators] = STATE(25),
    [sym_unit] = STATE(25),
    [sym_decorate] = STATE(25),
    [sym__unit] = STATE(12),
    [sym_func] = STATE(15),
    [sym_string] = STATE(25),
    [sym_list] = STATE(25),
    [sym_comment] = STATE(4),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_command_repeat1] = STATE(8),
    [anon_sym_RBRACE] = ACTIONS(51),
    [sym_arg_spliter] = ACTIONS(5),
    [anon_sym_PLUS_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_DASH_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(5),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
  },
  [5] = {
    [sym_block] = STATE(25),
    [sym_command] = STATE(30),
    [sym__command_unit] = STATE(22),
    [sym_operators] = STATE(25),
    [sym_unit] = STATE(25),
    [sym_decorate] = STATE(25),
    [sym__unit] = STATE(12),
    [sym_func] = STATE(15),
    [sym_string] = STATE(25),
    [sym_list] = STATE(25),
    [sym_comment] = STATE(5),
    [aux_sym_source_file_repeat1] = STATE(3),
    [aux_sym_command_repeat1] = STATE(8),
    [anon_sym_RBRACE] = ACTIONS(53),
    [sym_arg_spliter] = ACTIONS(5),
    [anon_sym_PLUS_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_DASH_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(5),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
  },
  [6] = {
    [sym_block] = STATE(25),
    [sym_command] = STATE(30),
    [sym__command_unit] = STATE(22),
    [sym_operators] = STATE(25),
    [sym_unit] = STATE(25),
    [sym_decorate] = STATE(25),
    [sym__unit] = STATE(12),
    [sym_func] = STATE(15),
    [sym_string] = STATE(25),
    [sym_list] = STATE(25),
    [sym_comment] = STATE(6),
    [aux_sym_source_file_repeat1] = STATE(4),
    [aux_sym_command_repeat1] = STATE(8),
    [anon_sym_RBRACE] = ACTIONS(55),
    [sym_arg_spliter] = ACTIONS(5),
    [anon_sym_PLUS_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_DASH_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(5),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
  },
  [7] = {
    [sym_block] = STATE(25),
    [sym_command] = STATE(30),
    [sym__command_unit] = STATE(22),
    [sym_operators] = STATE(25),
    [sym_unit] = STATE(25),
    [sym_decorate] = STATE(25),
    [sym__unit] = STATE(12),
    [sym_func] = STATE(15),
    [sym_string] = STATE(25),
    [sym_list] = STATE(25),
    [sym_comment] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_command_repeat1] = STATE(8),
    [ts_builtin_sym_end] = ACTIONS(57),
    [sym_arg_spliter] = ACTIONS(5),
    [anon_sym_PLUS_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_DASH_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(5),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
  },
  [8] = {
    [sym_block] = STATE(25),
    [sym__command_unit] = STATE(22),
    [sym_operators] = STATE(25),
    [sym_unit] = STATE(25),
    [sym_decorate] = STATE(25),
    [sym__unit] = STATE(12),
    [sym_func] = STATE(15),
    [sym_string] = STATE(25),
    [sym_list] = STATE(25),
    [sym_comment] = STATE(8),
    [aux_sym_command_repeat1] = STATE(9),
    [anon_sym_LF] = ACTIONS(59),
    [anon_sym_SEMI] = ACTIONS(61),
    [sym_arg_spliter] = ACTIONS(63),
    [anon_sym_PLUS_EQ] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(11),
    [anon_sym_DASH_EQ] = ACTIONS(11),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(11),
    [anon_sym_DASH_GT] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(65),
    [anon_sym_SQUOTE] = ACTIONS(67),
    [anon_sym_DQUOTE] = ACTIONS(69),
    [anon_sym_LBRACK] = ACTIONS(71),
    [sym_identifier] = ACTIONS(73),
    [sym_number] = ACTIONS(63),
    [sym_line_comment] = ACTIONS(75),
    [sym_block_comment] = ACTIONS(63),
  },
  [9] = {
    [sym_block] = STATE(25),
    [sym__command_unit] = STATE(22),
    [sym_operators] = STATE(25),
    [sym_unit] = STATE(25),
    [sym_decorate] = STATE(25),
    [sym__unit] = STATE(12),
    [sym_func] = STATE(15),
    [sym_string] = STATE(25),
    [sym_list] = STATE(25),
    [sym_comment] = STATE(9),
    [aux_sym_command_repeat1] = STATE(9),
    [anon_sym_LF] = ACTIONS(77),
    [anon_sym_SEMI] = ACTIONS(79),
    [sym_arg_spliter] = ACTIONS(81),
    [anon_sym_PLUS_EQ] = ACTIONS(84),
    [anon_sym_EQ] = ACTIONS(84),
    [anon_sym_DASH_EQ] = ACTIONS(84),
    [anon_sym_PLUS] = ACTIONS(84),
    [anon_sym_DASH] = ACTIONS(84),
    [anon_sym_TILDE] = ACTIONS(84),
    [anon_sym_DASH_GT] = ACTIONS(84),
    [anon_sym_AT] = ACTIONS(87),
    [anon_sym_SQUOTE] = ACTIONS(90),
    [anon_sym_DQUOTE] = ACTIONS(93),
    [anon_sym_LBRACK] = ACTIONS(96),
    [sym_identifier] = ACTIONS(99),
    [sym_number] = ACTIONS(81),
    [sym_line_comment] = ACTIONS(75),
    [sym_block_comment] = ACTIONS(63),
  },
  [10] = {
    [sym_block] = STATE(76),
    [sym__command_unit] = STATE(77),
    [sym_operators] = STATE(76),
    [sym_unit] = STATE(76),
    [sym_decorate] = STATE(76),
    [sym__unit] = STATE(38),
    [sym_func] = STATE(44),
    [sym_string] = STATE(76),
    [sym_list] = STATE(76),
    [sym_comment] = STATE(10),
    [sym_arg_spliter] = ACTIONS(102),
    [anon_sym_PLUS_EQ] = ACTIONS(104),
    [anon_sym_EQ] = ACTIONS(104),
    [anon_sym_DASH_EQ] = ACTIONS(104),
    [anon_sym_PLUS] = ACTIONS(106),
    [anon_sym_DASH] = ACTIONS(106),
    [anon_sym_TILDE] = ACTIONS(104),
    [anon_sym_DASH_GT] = ACTIONS(104),
    [anon_sym_AT] = ACTIONS(108),
    [anon_sym_SQUOTE] = ACTIONS(110),
    [anon_sym_DQUOTE] = ACTIONS(112),
    [anon_sym_LBRACK] = ACTIONS(114),
    [sym_identifier] = ACTIONS(116),
    [sym_number] = ACTIONS(102),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 7,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(120), 1,
      anon_sym_LF,
    ACTIONS(122), 1,
      anon_sym_LPAREN,
    STATE(11), 1,
      sym_comment,
    STATE(20), 1,
      sym_arg_block,
    ACTIONS(118), 17,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [38] = 7,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(126), 1,
      anon_sym_LF,
    ACTIONS(128), 1,
      anon_sym_DOT,
    STATE(12), 1,
      sym_comment,
    STATE(14), 1,
      aux_sym_unit_repeat1,
    ACTIONS(124), 16,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [75] = 6,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(132), 1,
      anon_sym_LF,
    ACTIONS(134), 1,
      anon_sym_DOT,
    STATE(13), 2,
      sym_comment,
      aux_sym_unit_repeat1,
    ACTIONS(130), 16,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [110] = 7,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(128), 1,
      anon_sym_DOT,
    ACTIONS(139), 1,
      anon_sym_LF,
    STATE(13), 1,
      aux_sym_unit_repeat1,
    STATE(14), 1,
      sym_comment,
    ACTIONS(137), 16,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [147] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(120), 1,
      anon_sym_LF,
    STATE(15), 1,
      sym_comment,
    ACTIONS(118), 17,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [179] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(132), 1,
      anon_sym_LF,
    STATE(16), 1,
      sym_comment,
    ACTIONS(130), 17,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [211] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(143), 1,
      anon_sym_LF,
    STATE(17), 1,
      sym_comment,
    ACTIONS(141), 17,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [243] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(147), 1,
      anon_sym_LF,
    STATE(18), 1,
      sym_comment,
    ACTIONS(145), 17,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [275] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(151), 1,
      anon_sym_LF,
    STATE(19), 1,
      sym_comment,
    ACTIONS(149), 17,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [307] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(155), 1,
      anon_sym_LF,
    STATE(20), 1,
      sym_comment,
    ACTIONS(153), 17,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [339] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(159), 1,
      anon_sym_LF,
    STATE(21), 1,
      sym_comment,
    ACTIONS(157), 17,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [371] = 6,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(161), 1,
      anon_sym_LBRACE,
    ACTIONS(163), 1,
      anon_sym_LF,
    STATE(22), 1,
      sym_comment,
    ACTIONS(165), 15,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [404] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(169), 1,
      anon_sym_LF,
    STATE(23), 1,
      sym_comment,
    ACTIONS(167), 16,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [435] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(173), 1,
      anon_sym_LF,
    STATE(24), 1,
      sym_comment,
    ACTIONS(171), 16,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [466] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(177), 1,
      anon_sym_LF,
    STATE(25), 1,
      sym_comment,
    ACTIONS(175), 16,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [497] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(181), 1,
      anon_sym_LF,
    STATE(26), 1,
      sym_comment,
    ACTIONS(179), 16,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [528] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(185), 1,
      anon_sym_LF,
    STATE(27), 1,
      sym_comment,
    ACTIONS(183), 16,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [559] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(189), 1,
      anon_sym_LF,
    STATE(28), 1,
      sym_comment,
    ACTIONS(187), 16,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [590] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(193), 1,
      anon_sym_LF,
    STATE(29), 1,
      sym_comment,
    ACTIONS(191), 16,
      anon_sym_LBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [621] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(30), 1,
      sym_comment,
    ACTIONS(197), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(195), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [651] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(31), 1,
      sym_comment,
    ACTIONS(201), 2,
      anon_sym_PLUS,
      anon_sym_DASH,
    ACTIONS(199), 14,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [681] = 12,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(203), 1,
      sym_arg_spliter,
    ACTIONS(208), 1,
      anon_sym_SQUOTE,
    ACTIONS(211), 1,
      anon_sym_DQUOTE,
    ACTIONS(214), 1,
      anon_sym_LBRACK,
    ACTIONS(217), 1,
      sym_identifier,
    STATE(38), 1,
      sym__unit,
    STATE(44), 1,
      sym_func,
    ACTIONS(206), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
    STATE(32), 2,
      sym_comment,
      aux_sym__args_repeat1,
    STATE(53), 3,
      sym_unit,
      sym_string,
      sym_list,
  [722] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(110), 1,
      anon_sym_SQUOTE,
    ACTIONS(112), 1,
      anon_sym_DQUOTE,
    ACTIONS(114), 1,
      anon_sym_LBRACK,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(220), 1,
      sym_arg_spliter,
    STATE(33), 1,
      sym_comment,
    STATE(34), 1,
      aux_sym__args_repeat1,
    STATE(38), 1,
      sym__unit,
    STATE(44), 1,
      sym_func,
    ACTIONS(222), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
    STATE(53), 3,
      sym_unit,
      sym_string,
      sym_list,
  [765] = 13,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(110), 1,
      anon_sym_SQUOTE,
    ACTIONS(112), 1,
      anon_sym_DQUOTE,
    ACTIONS(114), 1,
      anon_sym_LBRACK,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(220), 1,
      sym_arg_spliter,
    STATE(32), 1,
      aux_sym__args_repeat1,
    STATE(34), 1,
      sym_comment,
    STATE(38), 1,
      sym__unit,
    STATE(44), 1,
      sym_func,
    ACTIONS(224), 2,
      anon_sym_RPAREN,
      anon_sym_RBRACK,
    STATE(53), 3,
      sym_unit,
      sym_string,
      sym_list,
  [808] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(226), 1,
      anon_sym_LPAREN,
    STATE(35), 1,
      sym_comment,
    STATE(43), 1,
      sym_arg_block,
    ACTIONS(120), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [836] = 12,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(110), 1,
      anon_sym_SQUOTE,
    ACTIONS(112), 1,
      anon_sym_DQUOTE,
    ACTIONS(114), 1,
      anon_sym_LBRACK,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(228), 1,
      anon_sym_RPAREN,
    STATE(36), 1,
      sym_comment,
    STATE(38), 1,
      sym__unit,
    STATE(44), 1,
      sym_func,
    STATE(79), 1,
      sym__args,
    STATE(33), 3,
      sym_unit,
      sym_string,
      sym_list,
  [875] = 12,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(110), 1,
      anon_sym_SQUOTE,
    ACTIONS(112), 1,
      anon_sym_DQUOTE,
    ACTIONS(114), 1,
      anon_sym_LBRACK,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(230), 1,
      anon_sym_RPAREN,
    STATE(37), 1,
      sym_comment,
    STATE(38), 1,
      sym__unit,
    STATE(44), 1,
      sym_func,
    STATE(83), 1,
      sym__args,
    STATE(33), 3,
      sym_unit,
      sym_string,
      sym_list,
  [914] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(232), 1,
      anon_sym_DOT,
    STATE(38), 1,
      sym_comment,
    STATE(39), 1,
      aux_sym_unit_repeat1,
    ACTIONS(126), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [941] = 6,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(232), 1,
      anon_sym_DOT,
    STATE(39), 1,
      sym_comment,
    STATE(40), 1,
      aux_sym_unit_repeat1,
    ACTIONS(139), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [968] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(234), 1,
      anon_sym_DOT,
    STATE(40), 2,
      sym_comment,
      aux_sym_unit_repeat1,
    ACTIONS(132), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [993] = 12,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(110), 1,
      anon_sym_SQUOTE,
    ACTIONS(112), 1,
      anon_sym_DQUOTE,
    ACTIONS(114), 1,
      anon_sym_LBRACK,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(237), 1,
      anon_sym_RBRACK,
    STATE(38), 1,
      sym__unit,
    STATE(41), 1,
      sym_comment,
    STATE(44), 1,
      sym_func,
    STATE(82), 1,
      sym__args,
    STATE(33), 3,
      sym_unit,
      sym_string,
      sym_list,
  [1032] = 12,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(110), 1,
      anon_sym_SQUOTE,
    ACTIONS(112), 1,
      anon_sym_DQUOTE,
    ACTIONS(114), 1,
      anon_sym_LBRACK,
    ACTIONS(116), 1,
      sym_identifier,
    ACTIONS(239), 1,
      anon_sym_RBRACK,
    STATE(38), 1,
      sym__unit,
    STATE(42), 1,
      sym_comment,
    STATE(44), 1,
      sym_func,
    STATE(81), 1,
      sym__args,
    STATE(33), 3,
      sym_unit,
      sym_string,
      sym_list,
  [1071] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(43), 1,
      sym_comment,
    ACTIONS(155), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1093] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(44), 1,
      sym_comment,
    ACTIONS(120), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1115] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(45), 1,
      sym_comment,
    ACTIONS(132), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1137] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(46), 1,
      sym_comment,
    ACTIONS(159), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1159] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(47), 1,
      sym_comment,
    ACTIONS(151), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1181] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(48), 1,
      sym_comment,
    ACTIONS(147), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1203] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(49), 1,
      sym_comment,
    ACTIONS(143), 10,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1225] = 10,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(110), 1,
      anon_sym_SQUOTE,
    ACTIONS(112), 1,
      anon_sym_DQUOTE,
    ACTIONS(114), 1,
      anon_sym_LBRACK,
    ACTIONS(116), 1,
      sym_identifier,
    STATE(38), 1,
      sym__unit,
    STATE(44), 1,
      sym_func,
    STATE(50), 1,
      sym_comment,
    STATE(54), 3,
      sym_unit,
      sym_string,
      sym_list,
  [1258] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(51), 1,
      sym_comment,
    ACTIONS(189), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1279] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(52), 1,
      sym_comment,
    ACTIONS(185), 9,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1300] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(53), 1,
      sym_comment,
    ACTIONS(241), 7,
      sym_arg_spliter,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1319] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(54), 1,
      sym_comment,
    ACTIONS(206), 7,
      sym_arg_spliter,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1338] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    STATE(15), 1,
      sym_func,
    STATE(55), 1,
      sym_comment,
    STATE(16), 2,
      sym__unit,
      sym_string,
  [1364] = 8,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(110), 1,
      anon_sym_SQUOTE,
    ACTIONS(112), 1,
      anon_sym_DQUOTE,
    ACTIONS(116), 1,
      sym_identifier,
    STATE(44), 1,
      sym_func,
    STATE(56), 1,
      sym_comment,
    STATE(45), 2,
      sym__unit,
      sym_string,
  [1390] = 7,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(243), 1,
      sym_leading_key,
    ACTIONS(245), 1,
      anon_sym_DQUOTE,
    STATE(57), 1,
      sym_comment,
    STATE(58), 1,
      aux_sym_string_repeat2,
    ACTIONS(247), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1413] = 7,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(243), 1,
      sym_leading_key,
    ACTIONS(249), 1,
      anon_sym_DQUOTE,
    STATE(58), 1,
      sym_comment,
    STATE(61), 1,
      aux_sym_string_repeat2,
    ACTIONS(247), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1436] = 7,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(243), 1,
      sym_leading_key,
    ACTIONS(251), 1,
      anon_sym_DQUOTE,
    STATE(59), 1,
      sym_comment,
    STATE(60), 1,
      aux_sym_string_repeat2,
    ACTIONS(247), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1459] = 7,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(243), 1,
      sym_leading_key,
    ACTIONS(253), 1,
      anon_sym_DQUOTE,
    STATE(60), 1,
      sym_comment,
    STATE(61), 1,
      aux_sym_string_repeat2,
    ACTIONS(247), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1482] = 6,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(255), 1,
      sym_leading_key,
    ACTIONS(258), 1,
      anon_sym_DQUOTE,
    ACTIONS(260), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
    STATE(61), 2,
      sym_comment,
      aux_sym_string_repeat2,
  [1503] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    STATE(62), 1,
      sym_comment,
    ACTIONS(263), 2,
      sym_leading_key,
      anon_sym_DQUOTE,
    ACTIONS(265), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1521] = 6,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(251), 1,
      anon_sym_SQUOTE,
    STATE(63), 1,
      sym_comment,
    STATE(65), 1,
      aux_sym_string_repeat1,
    ACTIONS(267), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1541] = 6,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(245), 1,
      anon_sym_SQUOTE,
    STATE(64), 1,
      sym_comment,
    STATE(67), 1,
      aux_sym_string_repeat1,
    ACTIONS(267), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1561] = 6,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(253), 1,
      anon_sym_SQUOTE,
    STATE(65), 1,
      sym_comment,
    STATE(68), 1,
      aux_sym_string_repeat1,
    ACTIONS(267), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1581] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    STATE(66), 1,
      sym_comment,
    ACTIONS(269), 2,
      sym_leading_key,
      anon_sym_DQUOTE,
    ACTIONS(271), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1599] = 6,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(249), 1,
      anon_sym_SQUOTE,
    STATE(67), 1,
      sym_comment,
    STATE(68), 1,
      aux_sym_string_repeat1,
    ACTIONS(267), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1619] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(273), 1,
      anon_sym_SQUOTE,
    ACTIONS(275), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
    STATE(68), 2,
      sym_comment,
      aux_sym_string_repeat1,
  [1637] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    STATE(69), 1,
      sym_comment,
    ACTIONS(258), 2,
      sym_leading_key,
      anon_sym_DQUOTE,
    ACTIONS(278), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1655] = 5,
    ACTIONS(63), 1,
      sym_block_comment,
    ACTIONS(75), 1,
      sym_line_comment,
    ACTIONS(280), 1,
      anon_sym_SQUOTE,
    STATE(70), 1,
      sym_comment,
    ACTIONS(282), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1672] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(71), 1,
      sym_comment,
    ACTIONS(181), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1686] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(72), 1,
      sym_comment,
    ACTIONS(169), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1700] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(284), 1,
      anon_sym_LBRACE,
    ACTIONS(286), 1,
      sym_identifier,
    STATE(73), 1,
      sym_comment,
  [1716] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(74), 1,
      sym_comment,
    ACTIONS(173), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1730] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(75), 1,
      sym_comment,
    ACTIONS(193), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1744] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    STATE(76), 1,
      sym_comment,
    ACTIONS(177), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1758] = 5,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(288), 1,
      anon_sym_LBRACE,
    ACTIONS(290), 1,
      anon_sym_RBRACE,
    STATE(77), 1,
      sym_comment,
  [1774] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(292), 1,
      sym_identifier,
    STATE(78), 1,
      sym_comment,
  [1787] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(294), 1,
      anon_sym_RPAREN,
    STATE(79), 1,
      sym_comment,
  [1800] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(296), 1,
      ts_builtin_sym_end,
    STATE(80), 1,
      sym_comment,
  [1813] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(298), 1,
      anon_sym_RBRACK,
    STATE(81), 1,
      sym_comment,
  [1826] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(300), 1,
      anon_sym_RBRACK,
    STATE(82), 1,
      sym_comment,
  [1839] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(302), 1,
      anon_sym_RPAREN,
    STATE(83), 1,
      sym_comment,
  [1852] = 4,
    ACTIONS(3), 1,
      sym_line_comment,
    ACTIONS(5), 1,
      sym_block_comment,
    ACTIONS(304), 1,
      sym_identifier,
    STATE(84), 1,
      sym_comment,
  [1865] = 1,
    ACTIONS(306), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 38,
  [SMALL_STATE(13)] = 75,
  [SMALL_STATE(14)] = 110,
  [SMALL_STATE(15)] = 147,
  [SMALL_STATE(16)] = 179,
  [SMALL_STATE(17)] = 211,
  [SMALL_STATE(18)] = 243,
  [SMALL_STATE(19)] = 275,
  [SMALL_STATE(20)] = 307,
  [SMALL_STATE(21)] = 339,
  [SMALL_STATE(22)] = 371,
  [SMALL_STATE(23)] = 404,
  [SMALL_STATE(24)] = 435,
  [SMALL_STATE(25)] = 466,
  [SMALL_STATE(26)] = 497,
  [SMALL_STATE(27)] = 528,
  [SMALL_STATE(28)] = 559,
  [SMALL_STATE(29)] = 590,
  [SMALL_STATE(30)] = 621,
  [SMALL_STATE(31)] = 651,
  [SMALL_STATE(32)] = 681,
  [SMALL_STATE(33)] = 722,
  [SMALL_STATE(34)] = 765,
  [SMALL_STATE(35)] = 808,
  [SMALL_STATE(36)] = 836,
  [SMALL_STATE(37)] = 875,
  [SMALL_STATE(38)] = 914,
  [SMALL_STATE(39)] = 941,
  [SMALL_STATE(40)] = 968,
  [SMALL_STATE(41)] = 993,
  [SMALL_STATE(42)] = 1032,
  [SMALL_STATE(43)] = 1071,
  [SMALL_STATE(44)] = 1093,
  [SMALL_STATE(45)] = 1115,
  [SMALL_STATE(46)] = 1137,
  [SMALL_STATE(47)] = 1159,
  [SMALL_STATE(48)] = 1181,
  [SMALL_STATE(49)] = 1203,
  [SMALL_STATE(50)] = 1225,
  [SMALL_STATE(51)] = 1258,
  [SMALL_STATE(52)] = 1279,
  [SMALL_STATE(53)] = 1300,
  [SMALL_STATE(54)] = 1319,
  [SMALL_STATE(55)] = 1338,
  [SMALL_STATE(56)] = 1364,
  [SMALL_STATE(57)] = 1390,
  [SMALL_STATE(58)] = 1413,
  [SMALL_STATE(59)] = 1436,
  [SMALL_STATE(60)] = 1459,
  [SMALL_STATE(61)] = 1482,
  [SMALL_STATE(62)] = 1503,
  [SMALL_STATE(63)] = 1521,
  [SMALL_STATE(64)] = 1541,
  [SMALL_STATE(65)] = 1561,
  [SMALL_STATE(66)] = 1581,
  [SMALL_STATE(67)] = 1599,
  [SMALL_STATE(68)] = 1619,
  [SMALL_STATE(69)] = 1637,
  [SMALL_STATE(70)] = 1655,
  [SMALL_STATE(71)] = 1672,
  [SMALL_STATE(72)] = 1686,
  [SMALL_STATE(73)] = 1700,
  [SMALL_STATE(74)] = 1716,
  [SMALL_STATE(75)] = 1730,
  [SMALL_STATE(76)] = 1744,
  [SMALL_STATE(77)] = 1758,
  [SMALL_STATE(78)] = 1774,
  [SMALL_STATE(79)] = 1787,
  [SMALL_STATE(80)] = 1800,
  [SMALL_STATE(81)] = 1813,
  [SMALL_STATE(82)] = 1826,
  [SMALL_STATE(83)] = 1839,
  [SMALL_STATE(84)] = 1852,
  [SMALL_STATE(85)] = 1865,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(25),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(29),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(29),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(84),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(64),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(57),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(41),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(11),
  [49] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [55] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [61] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(84),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(64),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(85),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2),
  [81] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(25),
  [84] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(29),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(84),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(64),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(57),
  [96] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(41),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(11),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [106] = {.entry = {.count = 1, .reusable = false}}, SHIFT(75),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [118] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__unit, 1),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__unit, 1),
  [122] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unit, 1),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 1),
  [128] = {.entry = {.count = 1, .reusable = false}}, SHIFT(55),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_unit_repeat1, 2),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_unit_repeat1, 2),
  [134] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_unit_repeat1, 2), SHIFT_REPEAT(55),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unit, 2),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 2),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_block, 3),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_block, 3),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func, 2),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 2),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_block, 2),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_block, 2),
  [161] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 1),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 1),
  [167] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [171] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decorate, 2),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorate, 2),
  [175] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__command_unit, 1),
  [177] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__command_unit, 1),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [187] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3),
  [189] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [191] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operators, 1),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operators, 1),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2),
  [203] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(50),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2),
  [208] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(63),
  [211] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(59),
  [214] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(42),
  [217] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(35),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__args, 1),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__args, 2),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [234] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_unit_repeat1, 2), SHIFT_REPEAT(56),
  [237] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [239] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [241] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 1),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(73),
  [245] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [251] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [253] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [255] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2), SHIFT_REPEAT(73),
  [258] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2),
  [260] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2), SHIFT_REPEAT(62),
  [263] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 1),
  [265] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 1),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [269] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 4),
  [271] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 4),
  [273] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [275] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(70),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2),
  [280] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 1),
  [282] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 1),
  [284] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [286] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [288] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [290] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [292] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [296] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [298] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [300] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [306] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_groovy(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
