#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 95
#define LARGE_STATE_COUNT 19
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 2

enum {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_LF = 3,
  anon_sym_SEMI = 4,
  sym_arg_spliter = 5,
  sym_leading_key = 6,
  anon_sym_PLUS_EQ = 7,
  anon_sym_EQ = 8,
  anon_sym_DASH_EQ = 9,
  anon_sym_PLUS = 10,
  anon_sym_DASH = 11,
  anon_sym_TILDE = 12,
  anon_sym_DASH_GT = 13,
  anon_sym_AMP = 14,
  anon_sym_PIPE = 15,
  anon_sym_BANG_EQ = 16,
  anon_sym_BANG = 17,
  anon_sym_DOT = 18,
  anon_sym_AT = 19,
  anon_sym_LT = 20,
  anon_sym_GT = 21,
  anon_sym_LPAREN = 22,
  anon_sym_RPAREN = 23,
  anon_sym_SQUOTE = 24,
  aux_sym_string_token1 = 25,
  anon_sym_DQUOTE = 26,
  aux_sym_string_token2 = 27,
  anon_sym_LBRACK = 28,
  anon_sym_RBRACK = 29,
  sym_identifier = 30,
  sym_escape_sequence = 31,
  sym_number = 32,
  sym_line_comment = 33,
  sym_block_comment = 34,
  sym_source_file = 35,
  sym_block = 36,
  sym_command = 37,
  sym_end_command = 38,
  sym__command_unit = 39,
  sym_operators = 40,
  sym_unit = 41,
  sym_decorate = 42,
  sym__unit = 43,
  sym_generics_class = 44,
  sym_func = 45,
  sym_arg_block = 46,
  sym_string = 47,
  sym_list = 48,
  sym__args = 49,
  aux_sym_source_file_repeat1 = 50,
  aux_sym_command_repeat1 = 51,
  aux_sym_unit_repeat1 = 52,
  aux_sym_string_repeat1 = 53,
  aux_sym_string_repeat2 = 54,
  aux_sym__args_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LF] = "\n",
  [anon_sym_SEMI] = ";",
  [sym_arg_spliter] = "arg_spliter",
  [sym_leading_key] = "leading_key",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_EQ] = "=",
  [anon_sym_DASH_EQ] = "-=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_TILDE] = "~",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_AMP] = "&",
  [anon_sym_PIPE] = "|",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_BANG] = "!",
  [anon_sym_DOT] = ".",
  [anon_sym_AT] = "@",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_identifier] = "identifier",
  [sym_escape_sequence] = "escape_sequence",
  [sym_number] = "number",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym_block] = "block",
  [sym_command] = "command",
  [sym_end_command] = "end_command",
  [sym__command_unit] = "_command_unit",
  [sym_operators] = "operators",
  [sym_unit] = "unit",
  [sym_decorate] = "decorate",
  [sym__unit] = "_unit",
  [sym_generics_class] = "generics_class",
  [sym_func] = "func",
  [sym_arg_block] = "arg_block",
  [sym_string] = "string",
  [sym_list] = "list",
  [sym__args] = "_args",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_command_repeat1] = "command_repeat1",
  [aux_sym_unit_repeat1] = "unit_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
  [aux_sym__args_repeat1] = "_args_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_arg_spliter] = sym_arg_spliter,
  [sym_leading_key] = sym_leading_key,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DASH_EQ] = anon_sym_DASH_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_identifier] = sym_identifier,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_number] = sym_number,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym_block] = sym_block,
  [sym_command] = sym_command,
  [sym_end_command] = sym_end_command,
  [sym__command_unit] = sym__command_unit,
  [sym_operators] = sym_operators,
  [sym_unit] = sym_unit,
  [sym_decorate] = sym_decorate,
  [sym__unit] = sym__unit,
  [sym_generics_class] = sym_generics_class,
  [sym_func] = sym_func,
  [sym_arg_block] = sym_arg_block,
  [sym_string] = sym_string,
  [sym_list] = sym_list,
  [sym__args] = sym__args,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_command_repeat1] = aux_sym_command_repeat1,
  [aux_sym_unit_repeat1] = aux_sym_unit_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
  [aux_sym__args_repeat1] = aux_sym__args_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_arg_spliter] = {
    .visible = true,
    .named = true,
  },
  [sym_leading_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_end_command] = {
    .visible = true,
    .named = true,
  },
  [sym__command_unit] = {
    .visible = false,
    .named = true,
  },
  [sym_operators] = {
    .visible = true,
    .named = true,
  },
  [sym_unit] = {
    .visible = true,
    .named = true,
  },
  [sym_decorate] = {
    .visible = true,
    .named = true,
  },
  [sym__unit] = {
    .visible = false,
    .named = true,
  },
  [sym_generics_class] = {
    .visible = true,
    .named = true,
  },
  [sym_func] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_block] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__args] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unit_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__args_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_generics_type = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_generics_type] = "generics_type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_generics_type, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 3,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 16,
  [18] = 15,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 24,
  [30] = 25,
  [31] = 31,
  [32] = 32,
  [33] = 27,
  [34] = 32,
  [35] = 19,
  [36] = 26,
  [37] = 31,
  [38] = 28,
  [39] = 23,
  [40] = 40,
  [41] = 41,
  [42] = 41,
  [43] = 43,
  [44] = 43,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 21,
  [50] = 47,
  [51] = 51,
  [52] = 22,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 55,
  [57] = 55,
  [58] = 19,
  [59] = 59,
  [60] = 60,
  [61] = 59,
  [62] = 62,
  [63] = 60,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 23,
  [68] = 68,
  [69] = 69,
  [70] = 65,
  [71] = 22,
  [72] = 21,
  [73] = 69,
  [74] = 46,
  [75] = 51,
  [76] = 76,
  [77] = 40,
  [78] = 48,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 86,
  [87] = 86,
  [88] = 85,
  [89] = 84,
  [90] = 81,
  [91] = 80,
  [92] = 92,
  [93] = 92,
  [94] = 83,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(23);
      if (lookahead == '!') ADVANCE(40);
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '$') ADVANCE(29);
      if (lookahead == '&') ADVANCE(37);
      if (lookahead == '\'') ADVANCE(47);
      if (lookahead == '(') ADVANCE(45);
      if (lookahead == ')') ADVANCE(46);
      if (lookahead == '+') ADVANCE(33);
      if (lookahead == ',') ADVANCE(28);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == '.') ADVANCE(41);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '0') ADVANCE(68);
      if (lookahead == ';') ADVANCE(27);
      if (lookahead == '<') ADVANCE(43);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '>') ADVANCE(44);
      if (lookahead == '@') ADVANCE(42);
      if (lookahead == '[') ADVANCE(61);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == ']') ADVANCE(62);
      if (lookahead == '{') ADVANCE(24);
      if (lookahead == '|') ADVANCE(38);
      if (lookahead == '}') ADVANCE(25);
      if (lookahead == '~') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(22)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(26);
      if (lookahead == '!') ADVANCE(40);
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '&') ADVANCE(37);
      if (lookahead == '\'') ADVANCE(47);
      if (lookahead == '(') ADVANCE(45);
      if (lookahead == '+') ADVANCE(33);
      if (lookahead == ',') ADVANCE(28);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == '.') ADVANCE(41);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '0') ADVANCE(68);
      if (lookahead == ';') ADVANCE(27);
      if (lookahead == '<') ADVANCE(43);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '@') ADVANCE(42);
      if (lookahead == '[') ADVANCE(61);
      if (lookahead == '{') ADVANCE(24);
      if (lookahead == '|') ADVANCE(38);
      if (lookahead == '}') ADVANCE(25);
      if (lookahead == '~') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '$') ADVANCE(29);
      if (lookahead == '/') ADVANCE(56);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '^') ADVANCE(60);
      END_STATE();
    case 3:
      if (lookahead == '\'') ADVANCE(47);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == '\\') ADVANCE(7);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0) ADVANCE(53);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(77);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(78);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == 'u') ADVANCE(8);
      if (lookahead == 'x') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(66);
      if (lookahead != 0) ADVANCE(64);
      END_STATE();
    case 8:
      if (lookahead == '{') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      END_STATE();
    case 9:
      if (lookahead == '}') ADVANCE(64);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 10:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 11:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(70);
      END_STATE();
    case 12:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(71);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(64);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(72);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(9);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(17);
      END_STATE();
    case 22:
      if (eof) ADVANCE(23);
      if (lookahead == '!') ADVANCE(40);
      if (lookahead == '"') ADVANCE(54);
      if (lookahead == '$') ADVANCE(29);
      if (lookahead == '&') ADVANCE(37);
      if (lookahead == '\'') ADVANCE(47);
      if (lookahead == '(') ADVANCE(45);
      if (lookahead == ')') ADVANCE(46);
      if (lookahead == '+') ADVANCE(33);
      if (lookahead == ',') ADVANCE(28);
      if (lookahead == '-') ADVANCE(34);
      if (lookahead == '.') ADVANCE(41);
      if (lookahead == '/') ADVANCE(4);
      if (lookahead == '0') ADVANCE(68);
      if (lookahead == ';') ADVANCE(27);
      if (lookahead == '<') ADVANCE(43);
      if (lookahead == '=') ADVANCE(31);
      if (lookahead == '>') ADVANCE(44);
      if (lookahead == '@') ADVANCE(42);
      if (lookahead == '[') ADVANCE(61);
      if (lookahead == ']') ADVANCE(62);
      if (lookahead == '{') ADVANCE(24);
      if (lookahead == '|') ADVANCE(38);
      if (lookahead == '}') ADVANCE(25);
      if (lookahead == '~') ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(22)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(69);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_arg_spliter);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_leading_key);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_DASH_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '=') ADVANCE(30);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '>') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(39);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(51);
      if (lookahead == '/') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(53);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(50);
      if (lookahead == '/') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(51);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(50);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(49);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(53);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(53);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\n') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(58);
      if (lookahead == '/') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(60);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(57);
      if (lookahead == '/') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(58);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(58);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '/') ADVANCE(56);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(60);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(60);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(64);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(65);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_number);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(76);
      if (lookahead == '0') ADVANCE(73);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(11);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(10);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(12);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(18);
      if (lookahead == '_') ADVANCE(16);
      if (lookahead == 'n') ADVANCE(67);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(76);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(10);
      if (lookahead == '_') ADVANCE(13);
      if (lookahead == 'n') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(69);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(11);
      if (lookahead == 'n') ADVANCE(67);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(70);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(12);
      if (lookahead == 'n') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(71);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(18);
      if (lookahead == 'n') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(72);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(16);
      if (lookahead == 'n') ADVANCE(67);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(14);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(10);
      if (lookahead == '_') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(75);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 0},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 1},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 1},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 1},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 1},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 1},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 1},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 1},
  [49] = {.lex_state = 0},
  [50] = {.lex_state = 1},
  [51] = {.lex_state = 1},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 2},
  [60] = {.lex_state = 2},
  [61] = {.lex_state = 2},
  [62] = {.lex_state = 2},
  [63] = {.lex_state = 2},
  [64] = {.lex_state = 2},
  [65] = {.lex_state = 3},
  [66] = {.lex_state = 2},
  [67] = {.lex_state = 0},
  [68] = {.lex_state = 3},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 0},
  [72] = {.lex_state = 0},
  [73] = {.lex_state = 3},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_arg_spliter] = ACTIONS(1),
    [sym_leading_key] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DASH_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(82),
    [sym_block] = STATE(45),
    [sym_command] = STATE(9),
    [sym__command_unit] = STATE(45),
    [sym_operators] = STATE(45),
    [sym_unit] = STATE(45),
    [sym_decorate] = STATE(45),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(45),
    [sym_list] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym_command_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_arg_spliter] = ACTIONS(7),
    [anon_sym_PLUS_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_DASH_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [2] = {
    [sym_block] = STATE(45),
    [sym_command] = STATE(6),
    [sym_end_command] = STATE(92),
    [sym__command_unit] = STATE(45),
    [sym_operators] = STATE(45),
    [sym_unit] = STATE(45),
    [sym_decorate] = STATE(45),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(45),
    [sym_list] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_command_repeat1] = STATE(8),
    [anon_sym_RBRACE] = ACTIONS(23),
    [sym_arg_spliter] = ACTIONS(7),
    [anon_sym_PLUS_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_DASH_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [3] = {
    [sym_block] = STATE(45),
    [sym_command] = STATE(2),
    [sym_end_command] = STATE(90),
    [sym__command_unit] = STATE(45),
    [sym_operators] = STATE(45),
    [sym_unit] = STATE(45),
    [sym_decorate] = STATE(45),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(45),
    [sym_list] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_command_repeat1] = STATE(8),
    [anon_sym_RBRACE] = ACTIONS(25),
    [sym_arg_spliter] = ACTIONS(7),
    [anon_sym_PLUS_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_DASH_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [4] = {
    [sym_block] = STATE(45),
    [sym_command] = STATE(6),
    [sym_end_command] = STATE(93),
    [sym__command_unit] = STATE(45),
    [sym_operators] = STATE(45),
    [sym_unit] = STATE(45),
    [sym_decorate] = STATE(45),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(45),
    [sym_list] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_command_repeat1] = STATE(8),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym_arg_spliter] = ACTIONS(7),
    [anon_sym_PLUS_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_DASH_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [5] = {
    [sym_block] = STATE(45),
    [sym_command] = STATE(4),
    [sym_end_command] = STATE(81),
    [sym__command_unit] = STATE(45),
    [sym_operators] = STATE(45),
    [sym_unit] = STATE(45),
    [sym_decorate] = STATE(45),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(45),
    [sym_list] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(4),
    [aux_sym_command_repeat1] = STATE(8),
    [anon_sym_RBRACE] = ACTIONS(29),
    [sym_arg_spliter] = ACTIONS(7),
    [anon_sym_PLUS_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_DASH_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [6] = {
    [sym_block] = STATE(45),
    [sym_command] = STATE(6),
    [sym__command_unit] = STATE(45),
    [sym_operators] = STATE(45),
    [sym_unit] = STATE(45),
    [sym_decorate] = STATE(45),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(45),
    [sym_list] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_command_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(31),
    [sym_arg_spliter] = ACTIONS(33),
    [anon_sym_PLUS_EQ] = ACTIONS(36),
    [anon_sym_EQ] = ACTIONS(36),
    [anon_sym_DASH_EQ] = ACTIONS(36),
    [anon_sym_PLUS] = ACTIONS(39),
    [anon_sym_DASH] = ACTIONS(39),
    [anon_sym_TILDE] = ACTIONS(36),
    [anon_sym_DASH_GT] = ACTIONS(36),
    [anon_sym_AMP] = ACTIONS(36),
    [anon_sym_PIPE] = ACTIONS(36),
    [anon_sym_BANG_EQ] = ACTIONS(36),
    [anon_sym_BANG] = ACTIONS(39),
    [anon_sym_AT] = ACTIONS(42),
    [anon_sym_SQUOTE] = ACTIONS(45),
    [anon_sym_DQUOTE] = ACTIONS(48),
    [anon_sym_LBRACK] = ACTIONS(51),
    [sym_identifier] = ACTIONS(54),
    [sym_number] = ACTIONS(33),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [7] = {
    [sym_block] = STATE(45),
    [sym__command_unit] = STATE(45),
    [sym_operators] = STATE(45),
    [sym_unit] = STATE(45),
    [sym_decorate] = STATE(45),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(45),
    [sym_list] = STATE(45),
    [aux_sym_command_repeat1] = STATE(7),
    [anon_sym_RBRACE] = ACTIONS(57),
    [anon_sym_LF] = ACTIONS(59),
    [anon_sym_SEMI] = ACTIONS(57),
    [sym_arg_spliter] = ACTIONS(61),
    [anon_sym_PLUS_EQ] = ACTIONS(64),
    [anon_sym_EQ] = ACTIONS(64),
    [anon_sym_DASH_EQ] = ACTIONS(64),
    [anon_sym_PLUS] = ACTIONS(64),
    [anon_sym_DASH] = ACTIONS(64),
    [anon_sym_TILDE] = ACTIONS(64),
    [anon_sym_DASH_GT] = ACTIONS(64),
    [anon_sym_AMP] = ACTIONS(64),
    [anon_sym_PIPE] = ACTIONS(64),
    [anon_sym_BANG_EQ] = ACTIONS(64),
    [anon_sym_BANG] = ACTIONS(64),
    [anon_sym_AT] = ACTIONS(67),
    [anon_sym_SQUOTE] = ACTIONS(70),
    [anon_sym_DQUOTE] = ACTIONS(73),
    [anon_sym_LBRACK] = ACTIONS(76),
    [sym_identifier] = ACTIONS(79),
    [sym_number] = ACTIONS(61),
    [sym_line_comment] = ACTIONS(82),
    [sym_block_comment] = ACTIONS(82),
  },
  [8] = {
    [sym_block] = STATE(45),
    [sym__command_unit] = STATE(45),
    [sym_operators] = STATE(45),
    [sym_unit] = STATE(45),
    [sym_decorate] = STATE(45),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(45),
    [sym_list] = STATE(45),
    [aux_sym_command_repeat1] = STATE(7),
    [anon_sym_RBRACE] = ACTIONS(84),
    [anon_sym_LF] = ACTIONS(86),
    [anon_sym_SEMI] = ACTIONS(88),
    [sym_arg_spliter] = ACTIONS(90),
    [anon_sym_PLUS_EQ] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(11),
    [anon_sym_DASH_EQ] = ACTIONS(11),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(11),
    [anon_sym_DASH_GT] = ACTIONS(11),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(11),
    [anon_sym_BANG_EQ] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(92),
    [anon_sym_SQUOTE] = ACTIONS(94),
    [anon_sym_DQUOTE] = ACTIONS(96),
    [anon_sym_LBRACK] = ACTIONS(98),
    [sym_identifier] = ACTIONS(100),
    [sym_number] = ACTIONS(90),
    [sym_line_comment] = ACTIONS(82),
    [sym_block_comment] = ACTIONS(82),
  },
  [9] = {
    [sym_block] = STATE(45),
    [sym_command] = STATE(6),
    [sym__command_unit] = STATE(45),
    [sym_operators] = STATE(45),
    [sym_unit] = STATE(45),
    [sym_decorate] = STATE(45),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(45),
    [sym_list] = STATE(45),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_command_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(102),
    [sym_arg_spliter] = ACTIONS(7),
    [anon_sym_PLUS_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_DASH_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [10] = {
    [sym_block] = STATE(45),
    [sym__command_unit] = STATE(45),
    [sym_operators] = STATE(45),
    [sym_unit] = STATE(45),
    [sym_decorate] = STATE(45),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(45),
    [sym_list] = STATE(45),
    [aux_sym_command_repeat1] = STATE(7),
    [anon_sym_LF] = ACTIONS(86),
    [anon_sym_SEMI] = ACTIONS(88),
    [sym_arg_spliter] = ACTIONS(90),
    [anon_sym_PLUS_EQ] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(11),
    [anon_sym_DASH_EQ] = ACTIONS(11),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(11),
    [anon_sym_DASH_GT] = ACTIONS(11),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(11),
    [anon_sym_BANG_EQ] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(92),
    [anon_sym_SQUOTE] = ACTIONS(94),
    [anon_sym_DQUOTE] = ACTIONS(96),
    [anon_sym_LBRACK] = ACTIONS(98),
    [sym_identifier] = ACTIONS(100),
    [sym_number] = ACTIONS(90),
    [sym_line_comment] = ACTIONS(82),
    [sym_block_comment] = ACTIONS(82),
  },
  [11] = {
    [sym_operators] = STATE(11),
    [sym_unit] = STATE(11),
    [sym__unit] = STATE(39),
    [sym_generics_class] = STATE(39),
    [sym_func] = STATE(39),
    [sym_arg_block] = STATE(11),
    [sym_string] = STATE(11),
    [sym_list] = STATE(11),
    [aux_sym__args_repeat1] = STATE(11),
    [sym_arg_spliter] = ACTIONS(104),
    [anon_sym_PLUS_EQ] = ACTIONS(107),
    [anon_sym_EQ] = ACTIONS(107),
    [anon_sym_DASH_EQ] = ACTIONS(107),
    [anon_sym_PLUS] = ACTIONS(110),
    [anon_sym_DASH] = ACTIONS(110),
    [anon_sym_TILDE] = ACTIONS(107),
    [anon_sym_DASH_GT] = ACTIONS(107),
    [anon_sym_AMP] = ACTIONS(107),
    [anon_sym_PIPE] = ACTIONS(107),
    [anon_sym_BANG_EQ] = ACTIONS(107),
    [anon_sym_BANG] = ACTIONS(110),
    [anon_sym_LPAREN] = ACTIONS(113),
    [anon_sym_RPAREN] = ACTIONS(116),
    [anon_sym_SQUOTE] = ACTIONS(118),
    [anon_sym_DQUOTE] = ACTIONS(121),
    [anon_sym_LBRACK] = ACTIONS(124),
    [anon_sym_RBRACK] = ACTIONS(116),
    [sym_identifier] = ACTIONS(127),
    [sym_number] = ACTIONS(130),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [12] = {
    [sym_operators] = STATE(13),
    [sym_unit] = STATE(13),
    [sym__unit] = STATE(39),
    [sym_generics_class] = STATE(39),
    [sym_func] = STATE(39),
    [sym_arg_block] = STATE(13),
    [sym_string] = STATE(13),
    [sym_list] = STATE(13),
    [aux_sym__args_repeat1] = STATE(13),
    [sym_arg_spliter] = ACTIONS(133),
    [anon_sym_PLUS_EQ] = ACTIONS(135),
    [anon_sym_EQ] = ACTIONS(135),
    [anon_sym_DASH_EQ] = ACTIONS(135),
    [anon_sym_PLUS] = ACTIONS(137),
    [anon_sym_DASH] = ACTIONS(137),
    [anon_sym_TILDE] = ACTIONS(135),
    [anon_sym_DASH_GT] = ACTIONS(135),
    [anon_sym_AMP] = ACTIONS(135),
    [anon_sym_PIPE] = ACTIONS(135),
    [anon_sym_BANG_EQ] = ACTIONS(135),
    [anon_sym_BANG] = ACTIONS(137),
    [anon_sym_LPAREN] = ACTIONS(139),
    [anon_sym_RPAREN] = ACTIONS(141),
    [anon_sym_SQUOTE] = ACTIONS(143),
    [anon_sym_DQUOTE] = ACTIONS(145),
    [anon_sym_LBRACK] = ACTIONS(147),
    [anon_sym_RBRACK] = ACTIONS(141),
    [sym_identifier] = ACTIONS(149),
    [sym_number] = ACTIONS(151),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [13] = {
    [sym_operators] = STATE(11),
    [sym_unit] = STATE(11),
    [sym__unit] = STATE(39),
    [sym_generics_class] = STATE(39),
    [sym_func] = STATE(39),
    [sym_arg_block] = STATE(11),
    [sym_string] = STATE(11),
    [sym_list] = STATE(11),
    [aux_sym__args_repeat1] = STATE(11),
    [sym_arg_spliter] = ACTIONS(133),
    [anon_sym_PLUS_EQ] = ACTIONS(135),
    [anon_sym_EQ] = ACTIONS(135),
    [anon_sym_DASH_EQ] = ACTIONS(135),
    [anon_sym_PLUS] = ACTIONS(137),
    [anon_sym_DASH] = ACTIONS(137),
    [anon_sym_TILDE] = ACTIONS(135),
    [anon_sym_DASH_GT] = ACTIONS(135),
    [anon_sym_AMP] = ACTIONS(135),
    [anon_sym_PIPE] = ACTIONS(135),
    [anon_sym_BANG_EQ] = ACTIONS(135),
    [anon_sym_BANG] = ACTIONS(137),
    [anon_sym_LPAREN] = ACTIONS(139),
    [anon_sym_RPAREN] = ACTIONS(153),
    [anon_sym_SQUOTE] = ACTIONS(143),
    [anon_sym_DQUOTE] = ACTIONS(145),
    [anon_sym_LBRACK] = ACTIONS(147),
    [anon_sym_RBRACK] = ACTIONS(153),
    [sym_identifier] = ACTIONS(149),
    [sym_number] = ACTIONS(155),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [14] = {
    [sym_block] = STATE(79),
    [sym__command_unit] = STATE(79),
    [sym_operators] = STATE(79),
    [sym_unit] = STATE(79),
    [sym_decorate] = STATE(79),
    [sym__unit] = STATE(67),
    [sym_generics_class] = STATE(67),
    [sym_func] = STATE(67),
    [sym_string] = STATE(79),
    [sym_list] = STATE(79),
    [sym_arg_spliter] = ACTIONS(157),
    [anon_sym_PLUS_EQ] = ACTIONS(135),
    [anon_sym_EQ] = ACTIONS(135),
    [anon_sym_DASH_EQ] = ACTIONS(135),
    [anon_sym_PLUS] = ACTIONS(137),
    [anon_sym_DASH] = ACTIONS(137),
    [anon_sym_TILDE] = ACTIONS(135),
    [anon_sym_DASH_GT] = ACTIONS(135),
    [anon_sym_AMP] = ACTIONS(135),
    [anon_sym_PIPE] = ACTIONS(135),
    [anon_sym_BANG_EQ] = ACTIONS(135),
    [anon_sym_BANG] = ACTIONS(137),
    [anon_sym_AT] = ACTIONS(159),
    [anon_sym_SQUOTE] = ACTIONS(143),
    [anon_sym_DQUOTE] = ACTIONS(145),
    [anon_sym_LBRACK] = ACTIONS(147),
    [sym_identifier] = ACTIONS(161),
    [sym_number] = ACTIONS(157),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [15] = {
    [sym_operators] = STATE(12),
    [sym_unit] = STATE(12),
    [sym__unit] = STATE(39),
    [sym_generics_class] = STATE(39),
    [sym_func] = STATE(39),
    [sym_arg_block] = STATE(12),
    [sym_string] = STATE(12),
    [sym_list] = STATE(12),
    [sym__args] = STATE(87),
    [anon_sym_PLUS_EQ] = ACTIONS(135),
    [anon_sym_EQ] = ACTIONS(135),
    [anon_sym_DASH_EQ] = ACTIONS(135),
    [anon_sym_PLUS] = ACTIONS(137),
    [anon_sym_DASH] = ACTIONS(137),
    [anon_sym_TILDE] = ACTIONS(135),
    [anon_sym_DASH_GT] = ACTIONS(135),
    [anon_sym_AMP] = ACTIONS(135),
    [anon_sym_PIPE] = ACTIONS(135),
    [anon_sym_BANG_EQ] = ACTIONS(135),
    [anon_sym_BANG] = ACTIONS(137),
    [anon_sym_LPAREN] = ACTIONS(139),
    [anon_sym_SQUOTE] = ACTIONS(143),
    [anon_sym_DQUOTE] = ACTIONS(145),
    [anon_sym_LBRACK] = ACTIONS(147),
    [anon_sym_RBRACK] = ACTIONS(163),
    [sym_identifier] = ACTIONS(149),
    [sym_number] = ACTIONS(165),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [16] = {
    [sym_operators] = STATE(12),
    [sym_unit] = STATE(12),
    [sym__unit] = STATE(39),
    [sym_generics_class] = STATE(39),
    [sym_func] = STATE(39),
    [sym_arg_block] = STATE(12),
    [sym_string] = STATE(12),
    [sym_list] = STATE(12),
    [sym__args] = STATE(85),
    [anon_sym_PLUS_EQ] = ACTIONS(135),
    [anon_sym_EQ] = ACTIONS(135),
    [anon_sym_DASH_EQ] = ACTIONS(135),
    [anon_sym_PLUS] = ACTIONS(137),
    [anon_sym_DASH] = ACTIONS(137),
    [anon_sym_TILDE] = ACTIONS(135),
    [anon_sym_DASH_GT] = ACTIONS(135),
    [anon_sym_AMP] = ACTIONS(135),
    [anon_sym_PIPE] = ACTIONS(135),
    [anon_sym_BANG_EQ] = ACTIONS(135),
    [anon_sym_BANG] = ACTIONS(137),
    [anon_sym_LPAREN] = ACTIONS(139),
    [anon_sym_RPAREN] = ACTIONS(167),
    [anon_sym_SQUOTE] = ACTIONS(143),
    [anon_sym_DQUOTE] = ACTIONS(145),
    [anon_sym_LBRACK] = ACTIONS(147),
    [sym_identifier] = ACTIONS(149),
    [sym_number] = ACTIONS(165),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [17] = {
    [sym_operators] = STATE(12),
    [sym_unit] = STATE(12),
    [sym__unit] = STATE(39),
    [sym_generics_class] = STATE(39),
    [sym_func] = STATE(39),
    [sym_arg_block] = STATE(12),
    [sym_string] = STATE(12),
    [sym_list] = STATE(12),
    [sym__args] = STATE(88),
    [anon_sym_PLUS_EQ] = ACTIONS(135),
    [anon_sym_EQ] = ACTIONS(135),
    [anon_sym_DASH_EQ] = ACTIONS(135),
    [anon_sym_PLUS] = ACTIONS(137),
    [anon_sym_DASH] = ACTIONS(137),
    [anon_sym_TILDE] = ACTIONS(135),
    [anon_sym_DASH_GT] = ACTIONS(135),
    [anon_sym_AMP] = ACTIONS(135),
    [anon_sym_PIPE] = ACTIONS(135),
    [anon_sym_BANG_EQ] = ACTIONS(135),
    [anon_sym_BANG] = ACTIONS(137),
    [anon_sym_LPAREN] = ACTIONS(139),
    [anon_sym_RPAREN] = ACTIONS(169),
    [anon_sym_SQUOTE] = ACTIONS(143),
    [anon_sym_DQUOTE] = ACTIONS(145),
    [anon_sym_LBRACK] = ACTIONS(147),
    [sym_identifier] = ACTIONS(149),
    [sym_number] = ACTIONS(165),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [18] = {
    [sym_operators] = STATE(12),
    [sym_unit] = STATE(12),
    [sym__unit] = STATE(39),
    [sym_generics_class] = STATE(39),
    [sym_func] = STATE(39),
    [sym_arg_block] = STATE(12),
    [sym_string] = STATE(12),
    [sym_list] = STATE(12),
    [sym__args] = STATE(86),
    [anon_sym_PLUS_EQ] = ACTIONS(135),
    [anon_sym_EQ] = ACTIONS(135),
    [anon_sym_DASH_EQ] = ACTIONS(135),
    [anon_sym_PLUS] = ACTIONS(137),
    [anon_sym_DASH] = ACTIONS(137),
    [anon_sym_TILDE] = ACTIONS(135),
    [anon_sym_DASH_GT] = ACTIONS(135),
    [anon_sym_AMP] = ACTIONS(135),
    [anon_sym_PIPE] = ACTIONS(135),
    [anon_sym_BANG_EQ] = ACTIONS(135),
    [anon_sym_BANG] = ACTIONS(137),
    [anon_sym_LPAREN] = ACTIONS(139),
    [anon_sym_SQUOTE] = ACTIONS(143),
    [anon_sym_DQUOTE] = ACTIONS(145),
    [anon_sym_LBRACK] = ACTIONS(147),
    [anon_sym_RBRACK] = ACTIONS(171),
    [sym_identifier] = ACTIONS(149),
    [sym_number] = ACTIONS(165),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(175), 1,
      anon_sym_LF,
    ACTIONS(177), 1,
      anon_sym_LT,
    ACTIONS(179), 1,
      anon_sym_LPAREN,
    STATE(34), 1,
      sym_arg_block,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(173), 22,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [41] = 11,
    ACTIONS(139), 1,
      anon_sym_LPAREN,
    ACTIONS(143), 1,
      anon_sym_SQUOTE,
    ACTIONS(145), 1,
      anon_sym_DQUOTE,
    ACTIONS(147), 1,
      anon_sym_LBRACK,
    ACTIONS(149), 1,
      sym_identifier,
    ACTIONS(181), 1,
      sym_number,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(137), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(39), 3,
      sym__unit,
      sym_generics_class,
      sym_func,
    STATE(53), 5,
      sym_operators,
      sym_unit,
      sym_arg_block,
      sym_string,
      sym_list,
    ACTIONS(135), 8,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
  [91] = 5,
    ACTIONS(185), 1,
      anon_sym_LF,
    ACTIONS(187), 1,
      anon_sym_DOT,
    STATE(21), 1,
      aux_sym_unit_repeat1,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(183), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [128] = 5,
    ACTIONS(192), 1,
      anon_sym_LF,
    ACTIONS(194), 1,
      anon_sym_DOT,
    STATE(21), 1,
      aux_sym_unit_repeat1,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(190), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [165] = 5,
    ACTIONS(194), 1,
      anon_sym_DOT,
    ACTIONS(198), 1,
      anon_sym_LF,
    STATE(22), 1,
      aux_sym_unit_repeat1,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(196), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [202] = 3,
    ACTIONS(185), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(183), 22,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [234] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(202), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_DOT,
    ACTIONS(200), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
  [266] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(206), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_DOT,
    ACTIONS(204), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
  [298] = 3,
    ACTIONS(210), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(208), 22,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [330] = 3,
    ACTIONS(214), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(212), 22,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [362] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(183), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_DOT,
    ACTIONS(185), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
  [394] = 3,
    ACTIONS(200), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(202), 22,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [426] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(218), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_DOT,
    ACTIONS(216), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
  [458] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(222), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_DOT,
    ACTIONS(220), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
  [490] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(208), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_DOT,
    ACTIONS(210), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
  [522] = 3,
    ACTIONS(220), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(222), 22,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [554] = 6,
    ACTIONS(224), 1,
      anon_sym_LT,
    ACTIONS(226), 1,
      anon_sym_LPAREN,
    STATE(32), 1,
      sym_arg_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(173), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_DOT,
    ACTIONS(175), 16,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
  [592] = 3,
    ACTIONS(204), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(206), 22,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [624] = 3,
    ACTIONS(216), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(218), 22,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [656] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(212), 4,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
      anon_sym_DOT,
    ACTIONS(214), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
  [688] = 5,
    ACTIONS(229), 1,
      anon_sym_DOT,
    STATE(52), 1,
      aux_sym_unit_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(196), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(198), 17,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
  [723] = 3,
    ACTIONS(233), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(231), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [754] = 3,
    ACTIONS(237), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(235), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [785] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(235), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(237), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
  [816] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(241), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(239), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
  [847] = 3,
    ACTIONS(239), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(241), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [878] = 4,
    ACTIONS(243), 1,
      anon_sym_LBRACE,
    ACTIONS(247), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(245), 20,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [911] = 3,
    ACTIONS(251), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(249), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [942] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(255), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(253), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
  [973] = 3,
    ACTIONS(259), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(257), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [1004] = 5,
    ACTIONS(261), 1,
      anon_sym_DOT,
    STATE(49), 1,
      aux_sym_unit_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(183), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(185), 17,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
  [1039] = 3,
    ACTIONS(253), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(255), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [1070] = 3,
    ACTIONS(266), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(264), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [1101] = 5,
    ACTIONS(229), 1,
      anon_sym_DOT,
    STATE(49), 1,
      aux_sym_unit_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(190), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(192), 17,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
  [1136] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(268), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(116), 17,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
      sym_number,
  [1165] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(272), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(270), 17,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [1194] = 5,
    ACTIONS(143), 1,
      anon_sym_SQUOTE,
    ACTIONS(145), 1,
      anon_sym_DQUOTE,
    ACTIONS(161), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(29), 4,
      sym__unit,
      sym_generics_class,
      sym_func,
      sym_string,
  [1214] = 5,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(24), 4,
      sym__unit,
      sym_generics_class,
      sym_func,
      sym_string,
  [1234] = 5,
    ACTIONS(143), 1,
      anon_sym_SQUOTE,
    ACTIONS(145), 1,
      anon_sym_DQUOTE,
    ACTIONS(149), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(29), 4,
      sym__unit,
      sym_generics_class,
      sym_func,
      sym_string,
  [1254] = 5,
    ACTIONS(139), 1,
      anon_sym_LPAREN,
    ACTIONS(224), 1,
      anon_sym_LT,
    STATE(32), 1,
      sym_arg_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(175), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [1273] = 5,
    ACTIONS(274), 1,
      sym_leading_key,
    ACTIONS(276), 1,
      anon_sym_DQUOTE,
    STATE(62), 1,
      aux_sym_string_repeat2,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(278), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1291] = 5,
    ACTIONS(274), 1,
      sym_leading_key,
    ACTIONS(280), 1,
      anon_sym_DQUOTE,
    STATE(61), 1,
      aux_sym_string_repeat2,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(282), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1309] = 5,
    ACTIONS(274), 1,
      sym_leading_key,
    ACTIONS(284), 1,
      anon_sym_DQUOTE,
    STATE(62), 1,
      aux_sym_string_repeat2,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(278), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1327] = 5,
    ACTIONS(286), 1,
      sym_leading_key,
    ACTIONS(289), 1,
      anon_sym_DQUOTE,
    STATE(62), 1,
      aux_sym_string_repeat2,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(291), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1345] = 5,
    ACTIONS(274), 1,
      sym_leading_key,
    ACTIONS(294), 1,
      anon_sym_DQUOTE,
    STATE(59), 1,
      aux_sym_string_repeat2,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(296), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1363] = 3,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(298), 2,
      sym_leading_key,
      anon_sym_DQUOTE,
    ACTIONS(300), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1376] = 4,
    ACTIONS(280), 1,
      anon_sym_SQUOTE,
    STATE(73), 1,
      aux_sym_string_repeat1,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(302), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1391] = 3,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(289), 2,
      sym_leading_key,
      anon_sym_DQUOTE,
    ACTIONS(304), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1404] = 4,
    ACTIONS(306), 1,
      anon_sym_DOT,
    STATE(71), 1,
      aux_sym_unit_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(198), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1419] = 4,
    ACTIONS(308), 1,
      anon_sym_SQUOTE,
    STATE(68), 1,
      aux_sym_string_repeat1,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(310), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1434] = 4,
    ACTIONS(276), 1,
      anon_sym_SQUOTE,
    STATE(68), 1,
      aux_sym_string_repeat1,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(313), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1449] = 4,
    ACTIONS(294), 1,
      anon_sym_SQUOTE,
    STATE(69), 1,
      aux_sym_string_repeat1,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(315), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1464] = 4,
    ACTIONS(306), 1,
      anon_sym_DOT,
    STATE(72), 1,
      aux_sym_unit_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(192), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1479] = 4,
    ACTIONS(317), 1,
      anon_sym_DOT,
    STATE(72), 1,
      aux_sym_unit_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(185), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1494] = 4,
    ACTIONS(284), 1,
      anon_sym_SQUOTE,
    STATE(68), 1,
      aux_sym_string_repeat1,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(313), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1509] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(251), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1518] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(266), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1527] = 3,
    ACTIONS(320), 1,
      anon_sym_LBRACE,
    ACTIONS(322), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1538] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(233), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1547] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(259), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1556] = 3,
    ACTIONS(324), 1,
      anon_sym_LBRACE,
    ACTIONS(326), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1567] = 2,
    ACTIONS(328), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1575] = 2,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1583] = 2,
    ACTIONS(330), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1591] = 2,
    ACTIONS(332), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1599] = 2,
    ACTIONS(334), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1607] = 2,
    ACTIONS(336), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1615] = 2,
    ACTIONS(338), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1623] = 2,
    ACTIONS(340), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1631] = 2,
    ACTIONS(342), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1639] = 2,
    ACTIONS(344), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1647] = 2,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1655] = 2,
    ACTIONS(346), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1663] = 2,
    ACTIONS(348), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1671] = 2,
    ACTIONS(350), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1679] = 2,
    ACTIONS(352), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(19)] = 0,
  [SMALL_STATE(20)] = 41,
  [SMALL_STATE(21)] = 91,
  [SMALL_STATE(22)] = 128,
  [SMALL_STATE(23)] = 165,
  [SMALL_STATE(24)] = 202,
  [SMALL_STATE(25)] = 234,
  [SMALL_STATE(26)] = 266,
  [SMALL_STATE(27)] = 298,
  [SMALL_STATE(28)] = 330,
  [SMALL_STATE(29)] = 362,
  [SMALL_STATE(30)] = 394,
  [SMALL_STATE(31)] = 426,
  [SMALL_STATE(32)] = 458,
  [SMALL_STATE(33)] = 490,
  [SMALL_STATE(34)] = 522,
  [SMALL_STATE(35)] = 554,
  [SMALL_STATE(36)] = 592,
  [SMALL_STATE(37)] = 624,
  [SMALL_STATE(38)] = 656,
  [SMALL_STATE(39)] = 688,
  [SMALL_STATE(40)] = 723,
  [SMALL_STATE(41)] = 754,
  [SMALL_STATE(42)] = 785,
  [SMALL_STATE(43)] = 816,
  [SMALL_STATE(44)] = 847,
  [SMALL_STATE(45)] = 878,
  [SMALL_STATE(46)] = 911,
  [SMALL_STATE(47)] = 942,
  [SMALL_STATE(48)] = 973,
  [SMALL_STATE(49)] = 1004,
  [SMALL_STATE(50)] = 1039,
  [SMALL_STATE(51)] = 1070,
  [SMALL_STATE(52)] = 1101,
  [SMALL_STATE(53)] = 1136,
  [SMALL_STATE(54)] = 1165,
  [SMALL_STATE(55)] = 1194,
  [SMALL_STATE(56)] = 1214,
  [SMALL_STATE(57)] = 1234,
  [SMALL_STATE(58)] = 1254,
  [SMALL_STATE(59)] = 1273,
  [SMALL_STATE(60)] = 1291,
  [SMALL_STATE(61)] = 1309,
  [SMALL_STATE(62)] = 1327,
  [SMALL_STATE(63)] = 1345,
  [SMALL_STATE(64)] = 1363,
  [SMALL_STATE(65)] = 1376,
  [SMALL_STATE(66)] = 1391,
  [SMALL_STATE(67)] = 1404,
  [SMALL_STATE(68)] = 1419,
  [SMALL_STATE(69)] = 1434,
  [SMALL_STATE(70)] = 1449,
  [SMALL_STATE(71)] = 1464,
  [SMALL_STATE(72)] = 1479,
  [SMALL_STATE(73)] = 1494,
  [SMALL_STATE(74)] = 1509,
  [SMALL_STATE(75)] = 1518,
  [SMALL_STATE(76)] = 1527,
  [SMALL_STATE(77)] = 1538,
  [SMALL_STATE(78)] = 1547,
  [SMALL_STATE(79)] = 1556,
  [SMALL_STATE(80)] = 1567,
  [SMALL_STATE(81)] = 1575,
  [SMALL_STATE(82)] = 1583,
  [SMALL_STATE(83)] = 1591,
  [SMALL_STATE(84)] = 1599,
  [SMALL_STATE(85)] = 1607,
  [SMALL_STATE(86)] = 1615,
  [SMALL_STATE(87)] = 1623,
  [SMALL_STATE(88)] = 1631,
  [SMALL_STATE(89)] = 1639,
  [SMALL_STATE(90)] = 1647,
  [SMALL_STATE(91)] = 1655,
  [SMALL_STATE(92)] = 1663,
  [SMALL_STATE(93)] = 1671,
  [SMALL_STATE(94)] = 1679,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(45),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(50),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(50),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(91),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(70),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(63),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(15),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(19),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(45),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(50),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(91),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(70),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(63),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(15),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(19),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_command, 1),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(63),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(20),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(47),
  [110] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(47),
  [113] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(16),
  [116] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2),
  [118] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(65),
  [121] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(60),
  [124] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(18),
  [127] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(35),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(11),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__args, 1),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [153] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__args, 2),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [159] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__unit, 1),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__unit, 1),
  [177] = {.entry = {.count = 1, .reusable = false}}, SHIFT(83),
  [179] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [183] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_unit_repeat1, 2),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_unit_repeat1, 2),
  [187] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_unit_repeat1, 2), SHIFT_REPEAT(56),
  [190] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unit, 2),
  [192] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 2),
  [194] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unit, 1),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 1),
  [200] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_block, 2),
  [202] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_block, 2),
  [204] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generics_class, 4, .production_id = 1),
  [206] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_generics_class, 4, .production_id = 1),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_block, 3),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_block, 3),
  [216] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [218] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [220] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 2),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func, 2),
  [224] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__unit, 1), SHIFT(16),
  [229] = {.entry = {.count = 1, .reusable = false}}, SHIFT(57),
  [231] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4),
  [233] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4),
  [235] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2),
  [237] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3),
  [243] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 1),
  [247] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 1),
  [249] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [251] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [253] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operators, 1),
  [255] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operators, 1),
  [257] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 5),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 5),
  [261] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_unit_repeat1, 2), SHIFT_REPEAT(57),
  [264] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decorate, 2),
  [266] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorate, 2),
  [268] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__args_repeat1, 2),
  [270] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2),
  [272] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2),
  [274] = {.entry = {.count = 1, .reusable = false}}, SHIFT(76),
  [276] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [278] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [280] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [282] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [284] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [286] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2), SHIFT_REPEAT(76),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2),
  [291] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2), SHIFT_REPEAT(62),
  [294] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [298] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 4),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 4),
  [302] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [304] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2),
  [306] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [308] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [310] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(68),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [317] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_unit_repeat1, 2), SHIFT_REPEAT(55),
  [320] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [322] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [324] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [326] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [328] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [330] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [332] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [334] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [336] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [338] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [340] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [342] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [344] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [346] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [348] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [350] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [352] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_groovy(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
