#include <tree_sitter/parser.h>

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 95
#define LARGE_STATE_COUNT 15
#define SYMBOL_COUNT 56
#define ALIAS_COUNT 0
#define TOKEN_COUNT 35
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 2

enum {
  anon_sym_LBRACE = 1,
  anon_sym_RBRACE = 2,
  anon_sym_LF = 3,
  anon_sym_SEMI = 4,
  sym_arg_spliter = 5,
  sym_leading_key = 6,
  anon_sym_PLUS_EQ = 7,
  anon_sym_EQ = 8,
  anon_sym_DASH_EQ = 9,
  anon_sym_PLUS = 10,
  anon_sym_DASH = 11,
  anon_sym_TILDE = 12,
  anon_sym_DASH_GT = 13,
  anon_sym_AMP = 14,
  anon_sym_PIPE = 15,
  anon_sym_BANG_EQ = 16,
  anon_sym_BANG = 17,
  anon_sym_DOT = 18,
  anon_sym_AT = 19,
  anon_sym_LT = 20,
  anon_sym_GT = 21,
  anon_sym_LPAREN = 22,
  anon_sym_RPAREN = 23,
  anon_sym_SQUOTE = 24,
  aux_sym_string_token1 = 25,
  anon_sym_DQUOTE = 26,
  aux_sym_string_token2 = 27,
  anon_sym_LBRACK = 28,
  anon_sym_RBRACK = 29,
  sym_identifier = 30,
  sym_escape_sequence = 31,
  sym_number = 32,
  sym_line_comment = 33,
  sym_block_comment = 34,
  sym_source_file = 35,
  sym_block = 36,
  sym_command = 37,
  sym_end_command = 38,
  sym__command_unit = 39,
  sym_operators = 40,
  sym_unit = 41,
  sym_decorate = 42,
  sym__unit = 43,
  sym_generics_class = 44,
  sym_func = 45,
  sym_arg_block = 46,
  sym_string = 47,
  sym_list = 48,
  sym__args = 49,
  aux_sym_source_file_repeat1 = 50,
  aux_sym_command_repeat1 = 51,
  aux_sym_unit_repeat1 = 52,
  aux_sym_string_repeat1 = 53,
  aux_sym_string_repeat2 = 54,
  aux_sym__args_repeat1 = 55,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_LF] = "\n",
  [anon_sym_SEMI] = ";",
  [sym_arg_spliter] = "arg_spliter",
  [sym_leading_key] = "leading_key",
  [anon_sym_PLUS_EQ] = "+=",
  [anon_sym_EQ] = "=",
  [anon_sym_DASH_EQ] = "-=",
  [anon_sym_PLUS] = "+",
  [anon_sym_DASH] = "-",
  [anon_sym_TILDE] = "~",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_AMP] = "&",
  [anon_sym_PIPE] = "|",
  [anon_sym_BANG_EQ] = "!=",
  [anon_sym_BANG] = "!",
  [anon_sym_DOT] = ".",
  [anon_sym_AT] = "@",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_string_token1] = "string_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_string_token2] = "string_token2",
  [anon_sym_LBRACK] = "[",
  [anon_sym_RBRACK] = "]",
  [sym_identifier] = "identifier",
  [sym_escape_sequence] = "escape_sequence",
  [sym_number] = "number",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym_block] = "block",
  [sym_command] = "command",
  [sym_end_command] = "end_command",
  [sym__command_unit] = "_command_unit",
  [sym_operators] = "operators",
  [sym_unit] = "unit",
  [sym_decorate] = "decorate",
  [sym__unit] = "_unit",
  [sym_generics_class] = "generics_class",
  [sym_func] = "func",
  [sym_arg_block] = "arg_block",
  [sym_string] = "string",
  [sym_list] = "list",
  [sym__args] = "_args",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_command_repeat1] = "command_repeat1",
  [aux_sym_unit_repeat1] = "unit_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
  [aux_sym_string_repeat2] = "string_repeat2",
  [aux_sym__args_repeat1] = "_args_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_LF] = anon_sym_LF,
  [anon_sym_SEMI] = anon_sym_SEMI,
  [sym_arg_spliter] = sym_arg_spliter,
  [sym_leading_key] = sym_leading_key,
  [anon_sym_PLUS_EQ] = anon_sym_PLUS_EQ,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_DASH_EQ] = anon_sym_DASH_EQ,
  [anon_sym_PLUS] = anon_sym_PLUS,
  [anon_sym_DASH] = anon_sym_DASH,
  [anon_sym_TILDE] = anon_sym_TILDE,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_AMP] = anon_sym_AMP,
  [anon_sym_PIPE] = anon_sym_PIPE,
  [anon_sym_BANG_EQ] = anon_sym_BANG_EQ,
  [anon_sym_BANG] = anon_sym_BANG,
  [anon_sym_DOT] = anon_sym_DOT,
  [anon_sym_AT] = anon_sym_AT,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_string_token1] = aux_sym_string_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_string_token2] = aux_sym_string_token2,
  [anon_sym_LBRACK] = anon_sym_LBRACK,
  [anon_sym_RBRACK] = anon_sym_RBRACK,
  [sym_identifier] = sym_identifier,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_number] = sym_number,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym_block] = sym_block,
  [sym_command] = sym_command,
  [sym_end_command] = sym_end_command,
  [sym__command_unit] = sym__command_unit,
  [sym_operators] = sym_operators,
  [sym_unit] = sym_unit,
  [sym_decorate] = sym_decorate,
  [sym__unit] = sym__unit,
  [sym_generics_class] = sym_generics_class,
  [sym_func] = sym_func,
  [sym_arg_block] = sym_arg_block,
  [sym_string] = sym_string,
  [sym_list] = sym_list,
  [sym__args] = sym__args,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_command_repeat1] = aux_sym_command_repeat1,
  [aux_sym_unit_repeat1] = aux_sym_unit_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
  [aux_sym_string_repeat2] = aux_sym_string_repeat2,
  [aux_sym__args_repeat1] = aux_sym__args_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SEMI] = {
    .visible = true,
    .named = false,
  },
  [sym_arg_spliter] = {
    .visible = true,
    .named = true,
  },
  [sym_leading_key] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_PLUS_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PLUS] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_TILDE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AMP] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PIPE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_BANG] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DOT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACK] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACK] = {
    .visible = true,
    .named = false,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_block] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_end_command] = {
    .visible = true,
    .named = true,
  },
  [sym__command_unit] = {
    .visible = false,
    .named = true,
  },
  [sym_operators] = {
    .visible = true,
    .named = true,
  },
  [sym_unit] = {
    .visible = true,
    .named = true,
  },
  [sym_decorate] = {
    .visible = true,
    .named = true,
  },
  [sym__unit] = {
    .visible = false,
    .named = true,
  },
  [sym_generics_class] = {
    .visible = true,
    .named = true,
  },
  [sym_func] = {
    .visible = true,
    .named = true,
  },
  [sym_arg_block] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [sym_list] = {
    .visible = true,
    .named = true,
  },
  [sym__args] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_command_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_unit_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__args_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum {
  field_generics_type = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_generics_type] = "generics_type",
};

static const TSFieldMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_generics_type, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 2,
  [5] = 3,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 16,
  [18] = 18,
  [19] = 15,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 25,
  [32] = 24,
  [33] = 33,
  [34] = 28,
  [35] = 29,
  [36] = 27,
  [37] = 37,
  [38] = 38,
  [39] = 18,
  [40] = 40,
  [41] = 30,
  [42] = 42,
  [43] = 43,
  [44] = 26,
  [45] = 45,
  [46] = 46,
  [47] = 23,
  [48] = 33,
  [49] = 20,
  [50] = 43,
  [51] = 22,
  [52] = 46,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 55,
  [57] = 55,
  [58] = 18,
  [59] = 59,
  [60] = 60,
  [61] = 59,
  [62] = 62,
  [63] = 62,
  [64] = 22,
  [65] = 23,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 67,
  [72] = 68,
  [73] = 20,
  [74] = 45,
  [75] = 37,
  [76] = 40,
  [77] = 42,
  [78] = 78,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 83,
  [84] = 84,
  [85] = 85,
  [86] = 85,
  [87] = 87,
  [88] = 88,
  [89] = 80,
  [90] = 81,
  [91] = 82,
  [92] = 84,
  [93] = 88,
  [94] = 87,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(24);
      if (lookahead == '!') ADVANCE(43);
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == '&') ADVANCE(40);
      if (lookahead == '\'') ADVANCE(51);
      if (lookahead == '(') ADVANCE(49);
      if (lookahead == ')') ADVANCE(50);
      if (lookahead == '+') ADVANCE(35);
      if (lookahead == ',') ADVANCE(29);
      if (lookahead == '-') ADVANCE(37);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '0') ADVANCE(72);
      if (lookahead == ';') ADVANCE(28);
      if (lookahead == '<') ADVANCE(47);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '>') ADVANCE(48);
      if (lookahead == '@') ADVANCE(46);
      if (lookahead == '[') ADVANCE(65);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == ']') ADVANCE(66);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '|') ADVANCE(41);
      if (lookahead == '}') ADVANCE(26);
      if (lookahead == '~') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(23)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(73);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(27);
      if (lookahead == '!') ADVANCE(43);
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '&') ADVANCE(40);
      if (lookahead == '\'') ADVANCE(51);
      if (lookahead == '(') ADVANCE(49);
      if (lookahead == '+') ADVANCE(35);
      if (lookahead == ',') ADVANCE(29);
      if (lookahead == '-') ADVANCE(37);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '0') ADVANCE(72);
      if (lookahead == ';') ADVANCE(28);
      if (lookahead == '<') ADVANCE(47);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '@') ADVANCE(46);
      if (lookahead == '[') ADVANCE(65);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '|') ADVANCE(41);
      if (lookahead == '}') ADVANCE(26);
      if (lookahead == '~') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(1)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(73);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 2:
      if (lookahead == '!') ADVANCE(43);
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '&') ADVANCE(40);
      if (lookahead == '\'') ADVANCE(51);
      if (lookahead == '(') ADVANCE(49);
      if (lookahead == ')') ADVANCE(50);
      if (lookahead == '+') ADVANCE(34);
      if (lookahead == ',') ADVANCE(29);
      if (lookahead == '-') ADVANCE(36);
      if (lookahead == '.') ADVANCE(44);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '<') ADVANCE(47);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '[') ADVANCE(65);
      if (lookahead == ']') ADVANCE(66);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '|') ADVANCE(41);
      if (lookahead == '}') ADVANCE(26);
      if (lookahead == '~') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(2)
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == '/') ADVANCE(60);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '^') ADVANCE(64);
      END_STATE();
    case 4:
      if (lookahead == '\'') ADVANCE(51);
      if (lookahead == '/') ADVANCE(53);
      if (lookahead == '\\') ADVANCE(8);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(7);
      if (lookahead == '/') ADVANCE(81);
      END_STATE();
    case 6:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == '/') ADVANCE(82);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 7:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead != 0) ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == 'u') ADVANCE(9);
      if (lookahead == 'x') ADVANCE(22);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(70);
      if (lookahead != 0) ADVANCE(68);
      END_STATE();
    case 9:
      if (lookahead == '{') ADVANCE(20);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == '}') ADVANCE(68);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 11:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 12:
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(74);
      END_STATE();
    case 13:
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(75);
      END_STATE();
    case 14:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 15:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 16:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 17:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      END_STATE();
    case 18:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(68);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(76);
      END_STATE();
    case 20:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(10);
      END_STATE();
    case 21:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      END_STATE();
    case 22:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(18);
      END_STATE();
    case 23:
      if (eof) ADVANCE(24);
      if (lookahead == '!') ADVANCE(43);
      if (lookahead == '"') ADVANCE(58);
      if (lookahead == '$') ADVANCE(30);
      if (lookahead == '&') ADVANCE(40);
      if (lookahead == '\'') ADVANCE(51);
      if (lookahead == '(') ADVANCE(49);
      if (lookahead == ')') ADVANCE(50);
      if (lookahead == '+') ADVANCE(35);
      if (lookahead == ',') ADVANCE(29);
      if (lookahead == '-') ADVANCE(37);
      if (lookahead == '.') ADVANCE(45);
      if (lookahead == '/') ADVANCE(5);
      if (lookahead == '0') ADVANCE(72);
      if (lookahead == ';') ADVANCE(28);
      if (lookahead == '<') ADVANCE(47);
      if (lookahead == '=') ADVANCE(32);
      if (lookahead == '>') ADVANCE(48);
      if (lookahead == '@') ADVANCE(46);
      if (lookahead == '[') ADVANCE(65);
      if (lookahead == ']') ADVANCE(66);
      if (lookahead == '{') ADVANCE(25);
      if (lookahead == '|') ADVANCE(41);
      if (lookahead == '}') ADVANCE(26);
      if (lookahead == '~') ADVANCE(38);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') SKIP(23)
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(73);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_SEMI);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_arg_spliter);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_leading_key);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_PLUS_EQ);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_DASH_EQ);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '=') ADVANCE(31);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_PLUS);
      if (lookahead == '=') ADVANCE(31);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '=') ADVANCE(33);
      if (lookahead == '>') ADVANCE(39);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == '=') ADVANCE(33);
      if (lookahead == '>') ADVANCE(39);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(anon_sym_TILDE);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_AMP);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_PIPE);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_BANG_EQ);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_BANG);
      if (lookahead == '=') ADVANCE(42);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_DOT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_DOT);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '\n') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(52);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(55);
      if (lookahead == '/') ADVANCE(52);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(57);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(54);
      if (lookahead == '/') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(55);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '*') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead == '/') ADVANCE(53);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_string_token1);
      if (lookahead != 0 &&
          lookahead != '\'' &&
          lookahead != '\\') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '\n') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(59);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(62);
      if (lookahead == '/') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(64);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(61);
      if (lookahead == '/') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(62);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '*') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(62);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead == '/') ADVANCE(60);
      if (lookahead == '\t' ||
          lookahead == '\n' ||
          lookahead == '\r' ||
          lookahead == ' ') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(64);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(aux_sym_string_token2);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '$' &&
          lookahead != '\\' &&
          lookahead != '^') ADVANCE(64);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_LBRACK);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_RBRACK);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_escape_sequence);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(68);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_escape_sequence);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(69);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_number);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == '0') ADVANCE(77);
      if (lookahead == 'B' ||
          lookahead == 'b') ADVANCE(12);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      if (lookahead == 'O' ||
          lookahead == 'o') ADVANCE(13);
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(19);
      if (lookahead == '_') ADVANCE(17);
      if (lookahead == 'n') ADVANCE(71);
      if (('1' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(80);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      if (lookahead == '_') ADVANCE(14);
      if (lookahead == 'n') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(73);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(12);
      if (lookahead == 'n') ADVANCE(71);
      if (lookahead == '0' ||
          lookahead == '1') ADVANCE(74);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(13);
      if (lookahead == 'n') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '7')) ADVANCE(75);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(19);
      if (lookahead == 'n') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(76);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(17);
      if (lookahead == 'n') ADVANCE(71);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(77);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '_') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(78);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      if (lookahead == '_') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(79);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(81);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 0},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 1},
  [8] = {.lex_state = 1},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 2},
  [13] = {.lex_state = 2},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 2},
  [16] = {.lex_state = 2},
  [17] = {.lex_state = 2},
  [18] = {.lex_state = 1},
  [19] = {.lex_state = 2},
  [20] = {.lex_state = 1},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 1},
  [23] = {.lex_state = 1},
  [24] = {.lex_state = 1},
  [25] = {.lex_state = 1},
  [26] = {.lex_state = 1},
  [27] = {.lex_state = 1},
  [28] = {.lex_state = 1},
  [29] = {.lex_state = 1},
  [30] = {.lex_state = 1},
  [31] = {.lex_state = 2},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 1},
  [34] = {.lex_state = 2},
  [35] = {.lex_state = 2},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 1},
  [38] = {.lex_state = 1},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 1},
  [41] = {.lex_state = 2},
  [42] = {.lex_state = 1},
  [43] = {.lex_state = 1},
  [44] = {.lex_state = 2},
  [45] = {.lex_state = 1},
  [46] = {.lex_state = 1},
  [47] = {.lex_state = 2},
  [48] = {.lex_state = 2},
  [49] = {.lex_state = 2},
  [50] = {.lex_state = 2},
  [51] = {.lex_state = 2},
  [52] = {.lex_state = 2},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 2},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 0},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 3},
  [60] = {.lex_state = 3},
  [61] = {.lex_state = 3},
  [62] = {.lex_state = 3},
  [63] = {.lex_state = 3},
  [64] = {.lex_state = 0},
  [65] = {.lex_state = 0},
  [66] = {.lex_state = 4},
  [67] = {.lex_state = 4},
  [68] = {.lex_state = 4},
  [69] = {.lex_state = 3},
  [70] = {.lex_state = 3},
  [71] = {.lex_state = 4},
  [72] = {.lex_state = 4},
  [73] = {.lex_state = 0},
  [74] = {.lex_state = 0},
  [75] = {.lex_state = 0},
  [76] = {.lex_state = 0},
  [77] = {.lex_state = 0},
  [78] = {.lex_state = 0},
  [79] = {.lex_state = 0},
  [80] = {.lex_state = 0},
  [81] = {.lex_state = 0},
  [82] = {.lex_state = 0},
  [83] = {.lex_state = 0},
  [84] = {.lex_state = 0},
  [85] = {.lex_state = 0},
  [86] = {.lex_state = 0},
  [87] = {.lex_state = 0},
  [88] = {.lex_state = 0},
  [89] = {.lex_state = 0},
  [90] = {.lex_state = 0},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 0},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_SEMI] = ACTIONS(1),
    [sym_arg_spliter] = ACTIONS(1),
    [sym_leading_key] = ACTIONS(1),
    [anon_sym_PLUS_EQ] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_DASH_EQ] = ACTIONS(1),
    [anon_sym_PLUS] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [anon_sym_TILDE] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_AMP] = ACTIONS(1),
    [anon_sym_PIPE] = ACTIONS(1),
    [anon_sym_BANG_EQ] = ACTIONS(1),
    [anon_sym_BANG] = ACTIONS(1),
    [anon_sym_DOT] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACK] = ACTIONS(1),
    [anon_sym_RBRACK] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [1] = {
    [sym_source_file] = STATE(83),
    [sym_block] = STATE(38),
    [sym_command] = STATE(9),
    [sym__command_unit] = STATE(38),
    [sym_operators] = STATE(38),
    [sym_unit] = STATE(38),
    [sym_decorate] = STATE(38),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(38),
    [sym_list] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(9),
    [aux_sym_command_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_arg_spliter] = ACTIONS(7),
    [anon_sym_PLUS_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_DASH_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [2] = {
    [sym_block] = STATE(38),
    [sym_command] = STATE(6),
    [sym_end_command] = STATE(92),
    [sym__command_unit] = STATE(38),
    [sym_operators] = STATE(38),
    [sym_unit] = STATE(38),
    [sym_decorate] = STATE(38),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(38),
    [sym_list] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_command_repeat1] = STATE(8),
    [anon_sym_RBRACE] = ACTIONS(23),
    [sym_arg_spliter] = ACTIONS(7),
    [anon_sym_PLUS_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_DASH_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [3] = {
    [sym_block] = STATE(38),
    [sym_command] = STATE(2),
    [sym_end_command] = STATE(90),
    [sym__command_unit] = STATE(38),
    [sym_operators] = STATE(38),
    [sym_unit] = STATE(38),
    [sym_decorate] = STATE(38),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(38),
    [sym_list] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(2),
    [aux_sym_command_repeat1] = STATE(8),
    [anon_sym_RBRACE] = ACTIONS(25),
    [sym_arg_spliter] = ACTIONS(7),
    [anon_sym_PLUS_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_DASH_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [4] = {
    [sym_block] = STATE(38),
    [sym_command] = STATE(6),
    [sym_end_command] = STATE(84),
    [sym__command_unit] = STATE(38),
    [sym_operators] = STATE(38),
    [sym_unit] = STATE(38),
    [sym_decorate] = STATE(38),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(38),
    [sym_list] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_command_repeat1] = STATE(8),
    [anon_sym_RBRACE] = ACTIONS(27),
    [sym_arg_spliter] = ACTIONS(7),
    [anon_sym_PLUS_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_DASH_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [5] = {
    [sym_block] = STATE(38),
    [sym_command] = STATE(4),
    [sym_end_command] = STATE(81),
    [sym__command_unit] = STATE(38),
    [sym_operators] = STATE(38),
    [sym_unit] = STATE(38),
    [sym_decorate] = STATE(38),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(38),
    [sym_list] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(4),
    [aux_sym_command_repeat1] = STATE(8),
    [anon_sym_RBRACE] = ACTIONS(29),
    [sym_arg_spliter] = ACTIONS(7),
    [anon_sym_PLUS_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_DASH_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [6] = {
    [sym_block] = STATE(38),
    [sym_command] = STATE(6),
    [sym__command_unit] = STATE(38),
    [sym_operators] = STATE(38),
    [sym_unit] = STATE(38),
    [sym_decorate] = STATE(38),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(38),
    [sym_list] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_command_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(31),
    [anon_sym_RBRACE] = ACTIONS(31),
    [sym_arg_spliter] = ACTIONS(33),
    [anon_sym_PLUS_EQ] = ACTIONS(36),
    [anon_sym_EQ] = ACTIONS(36),
    [anon_sym_DASH_EQ] = ACTIONS(36),
    [anon_sym_PLUS] = ACTIONS(39),
    [anon_sym_DASH] = ACTIONS(39),
    [anon_sym_TILDE] = ACTIONS(36),
    [anon_sym_DASH_GT] = ACTIONS(36),
    [anon_sym_AMP] = ACTIONS(36),
    [anon_sym_PIPE] = ACTIONS(36),
    [anon_sym_BANG_EQ] = ACTIONS(36),
    [anon_sym_BANG] = ACTIONS(39),
    [anon_sym_AT] = ACTIONS(42),
    [anon_sym_SQUOTE] = ACTIONS(45),
    [anon_sym_DQUOTE] = ACTIONS(48),
    [anon_sym_LBRACK] = ACTIONS(51),
    [sym_identifier] = ACTIONS(54),
    [sym_number] = ACTIONS(33),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [7] = {
    [sym_block] = STATE(38),
    [sym__command_unit] = STATE(38),
    [sym_operators] = STATE(38),
    [sym_unit] = STATE(38),
    [sym_decorate] = STATE(38),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(38),
    [sym_list] = STATE(38),
    [aux_sym_command_repeat1] = STATE(7),
    [anon_sym_RBRACE] = ACTIONS(57),
    [anon_sym_LF] = ACTIONS(59),
    [anon_sym_SEMI] = ACTIONS(57),
    [sym_arg_spliter] = ACTIONS(61),
    [anon_sym_PLUS_EQ] = ACTIONS(64),
    [anon_sym_EQ] = ACTIONS(64),
    [anon_sym_DASH_EQ] = ACTIONS(64),
    [anon_sym_PLUS] = ACTIONS(64),
    [anon_sym_DASH] = ACTIONS(64),
    [anon_sym_TILDE] = ACTIONS(64),
    [anon_sym_DASH_GT] = ACTIONS(64),
    [anon_sym_AMP] = ACTIONS(64),
    [anon_sym_PIPE] = ACTIONS(64),
    [anon_sym_BANG_EQ] = ACTIONS(64),
    [anon_sym_BANG] = ACTIONS(64),
    [anon_sym_AT] = ACTIONS(67),
    [anon_sym_SQUOTE] = ACTIONS(70),
    [anon_sym_DQUOTE] = ACTIONS(73),
    [anon_sym_LBRACK] = ACTIONS(76),
    [sym_identifier] = ACTIONS(79),
    [sym_number] = ACTIONS(61),
    [sym_line_comment] = ACTIONS(82),
    [sym_block_comment] = ACTIONS(82),
  },
  [8] = {
    [sym_block] = STATE(38),
    [sym__command_unit] = STATE(38),
    [sym_operators] = STATE(38),
    [sym_unit] = STATE(38),
    [sym_decorate] = STATE(38),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(38),
    [sym_list] = STATE(38),
    [aux_sym_command_repeat1] = STATE(7),
    [anon_sym_RBRACE] = ACTIONS(84),
    [anon_sym_LF] = ACTIONS(86),
    [anon_sym_SEMI] = ACTIONS(88),
    [sym_arg_spliter] = ACTIONS(90),
    [anon_sym_PLUS_EQ] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(11),
    [anon_sym_DASH_EQ] = ACTIONS(11),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(11),
    [anon_sym_DASH_GT] = ACTIONS(11),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(11),
    [anon_sym_BANG_EQ] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(92),
    [anon_sym_SQUOTE] = ACTIONS(94),
    [anon_sym_DQUOTE] = ACTIONS(96),
    [anon_sym_LBRACK] = ACTIONS(98),
    [sym_identifier] = ACTIONS(100),
    [sym_number] = ACTIONS(90),
    [sym_line_comment] = ACTIONS(82),
    [sym_block_comment] = ACTIONS(82),
  },
  [9] = {
    [sym_block] = STATE(38),
    [sym_command] = STATE(6),
    [sym__command_unit] = STATE(38),
    [sym_operators] = STATE(38),
    [sym_unit] = STATE(38),
    [sym_decorate] = STATE(38),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(38),
    [sym_list] = STATE(38),
    [aux_sym_source_file_repeat1] = STATE(6),
    [aux_sym_command_repeat1] = STATE(10),
    [ts_builtin_sym_end] = ACTIONS(102),
    [sym_arg_spliter] = ACTIONS(7),
    [anon_sym_PLUS_EQ] = ACTIONS(9),
    [anon_sym_EQ] = ACTIONS(9),
    [anon_sym_DASH_EQ] = ACTIONS(9),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(9),
    [anon_sym_DASH_GT] = ACTIONS(9),
    [anon_sym_AMP] = ACTIONS(9),
    [anon_sym_PIPE] = ACTIONS(9),
    [anon_sym_BANG_EQ] = ACTIONS(9),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(13),
    [anon_sym_SQUOTE] = ACTIONS(15),
    [anon_sym_DQUOTE] = ACTIONS(17),
    [anon_sym_LBRACK] = ACTIONS(19),
    [sym_identifier] = ACTIONS(21),
    [sym_number] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [10] = {
    [sym_block] = STATE(38),
    [sym__command_unit] = STATE(38),
    [sym_operators] = STATE(38),
    [sym_unit] = STATE(38),
    [sym_decorate] = STATE(38),
    [sym__unit] = STATE(23),
    [sym_generics_class] = STATE(23),
    [sym_func] = STATE(23),
    [sym_string] = STATE(38),
    [sym_list] = STATE(38),
    [aux_sym_command_repeat1] = STATE(7),
    [anon_sym_LF] = ACTIONS(86),
    [anon_sym_SEMI] = ACTIONS(88),
    [sym_arg_spliter] = ACTIONS(90),
    [anon_sym_PLUS_EQ] = ACTIONS(11),
    [anon_sym_EQ] = ACTIONS(11),
    [anon_sym_DASH_EQ] = ACTIONS(11),
    [anon_sym_PLUS] = ACTIONS(11),
    [anon_sym_DASH] = ACTIONS(11),
    [anon_sym_TILDE] = ACTIONS(11),
    [anon_sym_DASH_GT] = ACTIONS(11),
    [anon_sym_AMP] = ACTIONS(11),
    [anon_sym_PIPE] = ACTIONS(11),
    [anon_sym_BANG_EQ] = ACTIONS(11),
    [anon_sym_BANG] = ACTIONS(11),
    [anon_sym_AT] = ACTIONS(92),
    [anon_sym_SQUOTE] = ACTIONS(94),
    [anon_sym_DQUOTE] = ACTIONS(96),
    [anon_sym_LBRACK] = ACTIONS(98),
    [sym_identifier] = ACTIONS(100),
    [sym_number] = ACTIONS(90),
    [sym_line_comment] = ACTIONS(82),
    [sym_block_comment] = ACTIONS(82),
  },
  [11] = {
    [sym_block] = STATE(78),
    [sym__command_unit] = STATE(78),
    [sym_operators] = STATE(78),
    [sym_unit] = STATE(78),
    [sym_decorate] = STATE(78),
    [sym__unit] = STATE(65),
    [sym_generics_class] = STATE(65),
    [sym_func] = STATE(65),
    [sym_string] = STATE(78),
    [sym_list] = STATE(78),
    [sym_arg_spliter] = ACTIONS(104),
    [anon_sym_PLUS_EQ] = ACTIONS(106),
    [anon_sym_EQ] = ACTIONS(106),
    [anon_sym_DASH_EQ] = ACTIONS(106),
    [anon_sym_PLUS] = ACTIONS(108),
    [anon_sym_DASH] = ACTIONS(108),
    [anon_sym_TILDE] = ACTIONS(106),
    [anon_sym_DASH_GT] = ACTIONS(106),
    [anon_sym_AMP] = ACTIONS(106),
    [anon_sym_PIPE] = ACTIONS(106),
    [anon_sym_BANG_EQ] = ACTIONS(106),
    [anon_sym_BANG] = ACTIONS(108),
    [anon_sym_AT] = ACTIONS(110),
    [anon_sym_SQUOTE] = ACTIONS(112),
    [anon_sym_DQUOTE] = ACTIONS(114),
    [anon_sym_LBRACK] = ACTIONS(116),
    [sym_identifier] = ACTIONS(118),
    [sym_number] = ACTIONS(104),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [12] = {
    [sym_operators] = STATE(12),
    [sym_unit] = STATE(12),
    [sym__unit] = STATE(47),
    [sym_generics_class] = STATE(47),
    [sym_func] = STATE(47),
    [sym_arg_block] = STATE(12),
    [sym_string] = STATE(12),
    [sym_list] = STATE(12),
    [aux_sym__args_repeat1] = STATE(12),
    [sym_arg_spliter] = ACTIONS(120),
    [anon_sym_PLUS_EQ] = ACTIONS(123),
    [anon_sym_EQ] = ACTIONS(123),
    [anon_sym_DASH_EQ] = ACTIONS(123),
    [anon_sym_PLUS] = ACTIONS(126),
    [anon_sym_DASH] = ACTIONS(126),
    [anon_sym_TILDE] = ACTIONS(123),
    [anon_sym_DASH_GT] = ACTIONS(123),
    [anon_sym_AMP] = ACTIONS(123),
    [anon_sym_PIPE] = ACTIONS(123),
    [anon_sym_BANG_EQ] = ACTIONS(123),
    [anon_sym_BANG] = ACTIONS(126),
    [anon_sym_LPAREN] = ACTIONS(129),
    [anon_sym_RPAREN] = ACTIONS(132),
    [anon_sym_SQUOTE] = ACTIONS(134),
    [anon_sym_DQUOTE] = ACTIONS(137),
    [anon_sym_LBRACK] = ACTIONS(140),
    [anon_sym_RBRACK] = ACTIONS(132),
    [sym_identifier] = ACTIONS(143),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [13] = {
    [sym_operators] = STATE(14),
    [sym_unit] = STATE(14),
    [sym__unit] = STATE(47),
    [sym_generics_class] = STATE(47),
    [sym_func] = STATE(47),
    [sym_arg_block] = STATE(14),
    [sym_string] = STATE(14),
    [sym_list] = STATE(14),
    [aux_sym__args_repeat1] = STATE(14),
    [sym_arg_spliter] = ACTIONS(146),
    [anon_sym_PLUS_EQ] = ACTIONS(106),
    [anon_sym_EQ] = ACTIONS(106),
    [anon_sym_DASH_EQ] = ACTIONS(106),
    [anon_sym_PLUS] = ACTIONS(108),
    [anon_sym_DASH] = ACTIONS(108),
    [anon_sym_TILDE] = ACTIONS(106),
    [anon_sym_DASH_GT] = ACTIONS(106),
    [anon_sym_AMP] = ACTIONS(106),
    [anon_sym_PIPE] = ACTIONS(106),
    [anon_sym_BANG_EQ] = ACTIONS(106),
    [anon_sym_BANG] = ACTIONS(108),
    [anon_sym_LPAREN] = ACTIONS(148),
    [anon_sym_RPAREN] = ACTIONS(150),
    [anon_sym_SQUOTE] = ACTIONS(112),
    [anon_sym_DQUOTE] = ACTIONS(114),
    [anon_sym_LBRACK] = ACTIONS(116),
    [anon_sym_RBRACK] = ACTIONS(150),
    [sym_identifier] = ACTIONS(152),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [14] = {
    [sym_operators] = STATE(12),
    [sym_unit] = STATE(12),
    [sym__unit] = STATE(47),
    [sym_generics_class] = STATE(47),
    [sym_func] = STATE(47),
    [sym_arg_block] = STATE(12),
    [sym_string] = STATE(12),
    [sym_list] = STATE(12),
    [aux_sym__args_repeat1] = STATE(12),
    [sym_arg_spliter] = ACTIONS(146),
    [anon_sym_PLUS_EQ] = ACTIONS(106),
    [anon_sym_EQ] = ACTIONS(106),
    [anon_sym_DASH_EQ] = ACTIONS(106),
    [anon_sym_PLUS] = ACTIONS(108),
    [anon_sym_DASH] = ACTIONS(108),
    [anon_sym_TILDE] = ACTIONS(106),
    [anon_sym_DASH_GT] = ACTIONS(106),
    [anon_sym_AMP] = ACTIONS(106),
    [anon_sym_PIPE] = ACTIONS(106),
    [anon_sym_BANG_EQ] = ACTIONS(106),
    [anon_sym_BANG] = ACTIONS(108),
    [anon_sym_LPAREN] = ACTIONS(148),
    [anon_sym_RPAREN] = ACTIONS(154),
    [anon_sym_SQUOTE] = ACTIONS(112),
    [anon_sym_DQUOTE] = ACTIONS(114),
    [anon_sym_LBRACK] = ACTIONS(116),
    [anon_sym_RBRACK] = ACTIONS(154),
    [sym_identifier] = ACTIONS(152),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 12,
    ACTIONS(112), 1,
      anon_sym_SQUOTE,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    ACTIONS(116), 1,
      anon_sym_LBRACK,
    ACTIONS(148), 1,
      anon_sym_LPAREN,
    ACTIONS(152), 1,
      sym_identifier,
    ACTIONS(156), 1,
      anon_sym_RBRACK,
    STATE(85), 1,
      sym__args,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(108), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(47), 3,
      sym__unit,
      sym_generics_class,
      sym_func,
    STATE(13), 5,
      sym_operators,
      sym_unit,
      sym_arg_block,
      sym_string,
      sym_list,
    ACTIONS(106), 8,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
  [53] = 12,
    ACTIONS(112), 1,
      anon_sym_SQUOTE,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    ACTIONS(116), 1,
      anon_sym_LBRACK,
    ACTIONS(148), 1,
      anon_sym_LPAREN,
    ACTIONS(152), 1,
      sym_identifier,
    ACTIONS(158), 1,
      anon_sym_RPAREN,
    STATE(93), 1,
      sym__args,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(108), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(47), 3,
      sym__unit,
      sym_generics_class,
      sym_func,
    STATE(13), 5,
      sym_operators,
      sym_unit,
      sym_arg_block,
      sym_string,
      sym_list,
    ACTIONS(106), 8,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
  [106] = 12,
    ACTIONS(112), 1,
      anon_sym_SQUOTE,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    ACTIONS(116), 1,
      anon_sym_LBRACK,
    ACTIONS(148), 1,
      anon_sym_LPAREN,
    ACTIONS(152), 1,
      sym_identifier,
    ACTIONS(160), 1,
      anon_sym_RPAREN,
    STATE(88), 1,
      sym__args,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(108), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(47), 3,
      sym__unit,
      sym_generics_class,
      sym_func,
    STATE(13), 5,
      sym_operators,
      sym_unit,
      sym_arg_block,
      sym_string,
      sym_list,
    ACTIONS(106), 8,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
  [159] = 6,
    ACTIONS(164), 1,
      anon_sym_LF,
    ACTIONS(166), 1,
      anon_sym_LT,
    ACTIONS(168), 1,
      anon_sym_LPAREN,
    STATE(25), 1,
      sym_arg_block,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(162), 22,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [200] = 12,
    ACTIONS(112), 1,
      anon_sym_SQUOTE,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    ACTIONS(116), 1,
      anon_sym_LBRACK,
    ACTIONS(148), 1,
      anon_sym_LPAREN,
    ACTIONS(152), 1,
      sym_identifier,
    ACTIONS(170), 1,
      anon_sym_RBRACK,
    STATE(86), 1,
      sym__args,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(108), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(47), 3,
      sym__unit,
      sym_generics_class,
      sym_func,
    STATE(13), 5,
      sym_operators,
      sym_unit,
      sym_arg_block,
      sym_string,
      sym_list,
    ACTIONS(106), 8,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
  [253] = 5,
    ACTIONS(174), 1,
      anon_sym_LF,
    ACTIONS(176), 1,
      anon_sym_DOT,
    STATE(20), 1,
      aux_sym_unit_repeat1,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(172), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [290] = 10,
    ACTIONS(112), 1,
      anon_sym_SQUOTE,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    ACTIONS(116), 1,
      anon_sym_LBRACK,
    ACTIONS(148), 1,
      anon_sym_LPAREN,
    ACTIONS(152), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(108), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    STATE(47), 3,
      sym__unit,
      sym_generics_class,
      sym_func,
    STATE(54), 5,
      sym_operators,
      sym_unit,
      sym_arg_block,
      sym_string,
      sym_list,
    ACTIONS(106), 8,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
  [337] = 5,
    ACTIONS(181), 1,
      anon_sym_LF,
    ACTIONS(183), 1,
      anon_sym_DOT,
    STATE(20), 1,
      aux_sym_unit_repeat1,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(179), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [374] = 5,
    ACTIONS(183), 1,
      anon_sym_DOT,
    ACTIONS(187), 1,
      anon_sym_LF,
    STATE(22), 1,
      aux_sym_unit_repeat1,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(185), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [411] = 3,
    ACTIONS(174), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(172), 22,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [443] = 3,
    ACTIONS(191), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(189), 22,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [475] = 3,
    ACTIONS(195), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(193), 22,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [507] = 3,
    ACTIONS(199), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(197), 22,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [539] = 3,
    ACTIONS(203), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(201), 22,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [571] = 3,
    ACTIONS(207), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(205), 22,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [603] = 3,
    ACTIONS(211), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(209), 22,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_DOT,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [635] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(189), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(191), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [666] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(172), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(174), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [697] = 3,
    ACTIONS(215), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(213), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [728] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(201), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(203), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [759] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(205), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(207), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [790] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(197), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(199), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [821] = 3,
    ACTIONS(219), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(217), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [852] = 4,
    ACTIONS(221), 1,
      anon_sym_LBRACE,
    ACTIONS(225), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(223), 20,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [885] = 6,
    ACTIONS(227), 1,
      anon_sym_LT,
    ACTIONS(229), 1,
      anon_sym_LPAREN,
    STATE(31), 1,
      sym_arg_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(162), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(164), 16,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_DOT,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [922] = 3,
    ACTIONS(234), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(232), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [953] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(209), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(211), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [984] = 3,
    ACTIONS(238), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(236), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [1015] = 3,
    ACTIONS(242), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(240), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [1046] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(193), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(195), 19,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_DOT,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1077] = 3,
    ACTIONS(246), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(244), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [1108] = 3,
    ACTIONS(250), 1,
      anon_sym_LF,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(248), 21,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_SEMI,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_BANG,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [1139] = 5,
    ACTIONS(252), 1,
      anon_sym_DOT,
    STATE(51), 1,
      aux_sym_unit_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(185), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(187), 16,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1173] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(213), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(215), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1203] = 5,
    ACTIONS(254), 1,
      anon_sym_DOT,
    STATE(49), 1,
      aux_sym_unit_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(172), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(174), 16,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1237] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(240), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(242), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1267] = 5,
    ACTIONS(252), 1,
      anon_sym_DOT,
    STATE(49), 1,
      aux_sym_unit_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(179), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(181), 16,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1301] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(248), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(250), 18,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1331] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(259), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(257), 17,
      ts_builtin_sym_end,
      anon_sym_RBRACE,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_AT,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      sym_identifier,
      sym_number,
  [1360] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(261), 3,
      anon_sym_PLUS,
      anon_sym_DASH,
      anon_sym_BANG,
    ACTIONS(132), 16,
      sym_arg_spliter,
      anon_sym_PLUS_EQ,
      anon_sym_EQ,
      anon_sym_DASH_EQ,
      anon_sym_TILDE,
      anon_sym_DASH_GT,
      anon_sym_AMP,
      anon_sym_PIPE,
      anon_sym_BANG_EQ,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      anon_sym_SQUOTE,
      anon_sym_DQUOTE,
      anon_sym_LBRACK,
      anon_sym_RBRACK,
      sym_identifier,
  [1388] = 5,
    ACTIONS(112), 1,
      anon_sym_SQUOTE,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    ACTIONS(118), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(32), 4,
      sym__unit,
      sym_generics_class,
      sym_func,
      sym_string,
  [1408] = 5,
    ACTIONS(15), 1,
      anon_sym_SQUOTE,
    ACTIONS(17), 1,
      anon_sym_DQUOTE,
    ACTIONS(21), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(24), 4,
      sym__unit,
      sym_generics_class,
      sym_func,
      sym_string,
  [1428] = 5,
    ACTIONS(112), 1,
      anon_sym_SQUOTE,
    ACTIONS(114), 1,
      anon_sym_DQUOTE,
    ACTIONS(152), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(32), 4,
      sym__unit,
      sym_generics_class,
      sym_func,
      sym_string,
  [1448] = 5,
    ACTIONS(148), 1,
      anon_sym_LPAREN,
    ACTIONS(227), 1,
      anon_sym_LT,
    STATE(31), 1,
      sym_arg_block,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(164), 3,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
      anon_sym_DOT,
  [1467] = 5,
    ACTIONS(263), 1,
      sym_leading_key,
    ACTIONS(265), 1,
      anon_sym_DQUOTE,
    STATE(62), 1,
      aux_sym_string_repeat2,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(267), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1485] = 5,
    ACTIONS(269), 1,
      sym_leading_key,
    ACTIONS(272), 1,
      anon_sym_DQUOTE,
    STATE(60), 1,
      aux_sym_string_repeat2,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(274), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1503] = 5,
    ACTIONS(263), 1,
      sym_leading_key,
    ACTIONS(277), 1,
      anon_sym_DQUOTE,
    STATE(63), 1,
      aux_sym_string_repeat2,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(279), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1521] = 5,
    ACTIONS(263), 1,
      sym_leading_key,
    ACTIONS(281), 1,
      anon_sym_DQUOTE,
    STATE(60), 1,
      aux_sym_string_repeat2,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(283), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1539] = 5,
    ACTIONS(263), 1,
      sym_leading_key,
    ACTIONS(285), 1,
      anon_sym_DQUOTE,
    STATE(60), 1,
      aux_sym_string_repeat2,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(283), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1557] = 4,
    ACTIONS(287), 1,
      anon_sym_DOT,
    STATE(73), 1,
      aux_sym_unit_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(181), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1572] = 4,
    ACTIONS(287), 1,
      anon_sym_DOT,
    STATE(64), 1,
      aux_sym_unit_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(187), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1587] = 4,
    ACTIONS(289), 1,
      anon_sym_SQUOTE,
    STATE(66), 1,
      aux_sym_string_repeat1,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(291), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1602] = 4,
    ACTIONS(285), 1,
      anon_sym_SQUOTE,
    STATE(66), 1,
      aux_sym_string_repeat1,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(294), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1617] = 4,
    ACTIONS(277), 1,
      anon_sym_SQUOTE,
    STATE(67), 1,
      aux_sym_string_repeat1,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(296), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1632] = 3,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(298), 2,
      sym_leading_key,
      anon_sym_DQUOTE,
    ACTIONS(300), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1645] = 3,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(272), 2,
      sym_leading_key,
      anon_sym_DQUOTE,
    ACTIONS(302), 2,
      aux_sym_string_token2,
      sym_escape_sequence,
  [1658] = 4,
    ACTIONS(281), 1,
      anon_sym_SQUOTE,
    STATE(66), 1,
      aux_sym_string_repeat1,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(294), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1673] = 4,
    ACTIONS(265), 1,
      anon_sym_SQUOTE,
    STATE(71), 1,
      aux_sym_string_repeat1,
    ACTIONS(82), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(304), 2,
      aux_sym_string_token1,
      sym_escape_sequence,
  [1688] = 4,
    ACTIONS(306), 1,
      anon_sym_DOT,
    STATE(73), 1,
      aux_sym_unit_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(174), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1703] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(246), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1712] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(219), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1721] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(234), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1730] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(238), 2,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1739] = 3,
    ACTIONS(309), 1,
      anon_sym_LBRACE,
    ACTIONS(311), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1750] = 3,
    ACTIONS(313), 1,
      anon_sym_LBRACE,
    ACTIONS(315), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1761] = 2,
    ACTIONS(317), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1769] = 2,
    ACTIONS(27), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1777] = 2,
    ACTIONS(319), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1785] = 2,
    ACTIONS(321), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1793] = 2,
    ACTIONS(323), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1801] = 2,
    ACTIONS(325), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1809] = 2,
    ACTIONS(327), 1,
      anon_sym_RBRACK,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1817] = 2,
    ACTIONS(329), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1825] = 2,
    ACTIONS(331), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1833] = 2,
    ACTIONS(333), 1,
      anon_sym_GT,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1841] = 2,
    ACTIONS(23), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1849] = 2,
    ACTIONS(335), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1857] = 2,
    ACTIONS(337), 1,
      anon_sym_RBRACE,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1865] = 2,
    ACTIONS(339), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [1873] = 2,
    ACTIONS(341), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(15)] = 0,
  [SMALL_STATE(16)] = 53,
  [SMALL_STATE(17)] = 106,
  [SMALL_STATE(18)] = 159,
  [SMALL_STATE(19)] = 200,
  [SMALL_STATE(20)] = 253,
  [SMALL_STATE(21)] = 290,
  [SMALL_STATE(22)] = 337,
  [SMALL_STATE(23)] = 374,
  [SMALL_STATE(24)] = 411,
  [SMALL_STATE(25)] = 443,
  [SMALL_STATE(26)] = 475,
  [SMALL_STATE(27)] = 507,
  [SMALL_STATE(28)] = 539,
  [SMALL_STATE(29)] = 571,
  [SMALL_STATE(30)] = 603,
  [SMALL_STATE(31)] = 635,
  [SMALL_STATE(32)] = 666,
  [SMALL_STATE(33)] = 697,
  [SMALL_STATE(34)] = 728,
  [SMALL_STATE(35)] = 759,
  [SMALL_STATE(36)] = 790,
  [SMALL_STATE(37)] = 821,
  [SMALL_STATE(38)] = 852,
  [SMALL_STATE(39)] = 885,
  [SMALL_STATE(40)] = 922,
  [SMALL_STATE(41)] = 953,
  [SMALL_STATE(42)] = 984,
  [SMALL_STATE(43)] = 1015,
  [SMALL_STATE(44)] = 1046,
  [SMALL_STATE(45)] = 1077,
  [SMALL_STATE(46)] = 1108,
  [SMALL_STATE(47)] = 1139,
  [SMALL_STATE(48)] = 1173,
  [SMALL_STATE(49)] = 1203,
  [SMALL_STATE(50)] = 1237,
  [SMALL_STATE(51)] = 1267,
  [SMALL_STATE(52)] = 1301,
  [SMALL_STATE(53)] = 1331,
  [SMALL_STATE(54)] = 1360,
  [SMALL_STATE(55)] = 1388,
  [SMALL_STATE(56)] = 1408,
  [SMALL_STATE(57)] = 1428,
  [SMALL_STATE(58)] = 1448,
  [SMALL_STATE(59)] = 1467,
  [SMALL_STATE(60)] = 1485,
  [SMALL_STATE(61)] = 1503,
  [SMALL_STATE(62)] = 1521,
  [SMALL_STATE(63)] = 1539,
  [SMALL_STATE(64)] = 1557,
  [SMALL_STATE(65)] = 1572,
  [SMALL_STATE(66)] = 1587,
  [SMALL_STATE(67)] = 1602,
  [SMALL_STATE(68)] = 1617,
  [SMALL_STATE(69)] = 1632,
  [SMALL_STATE(70)] = 1645,
  [SMALL_STATE(71)] = 1658,
  [SMALL_STATE(72)] = 1673,
  [SMALL_STATE(73)] = 1688,
  [SMALL_STATE(74)] = 1703,
  [SMALL_STATE(75)] = 1712,
  [SMALL_STATE(76)] = 1721,
  [SMALL_STATE(77)] = 1730,
  [SMALL_STATE(78)] = 1739,
  [SMALL_STATE(79)] = 1750,
  [SMALL_STATE(80)] = 1761,
  [SMALL_STATE(81)] = 1769,
  [SMALL_STATE(82)] = 1777,
  [SMALL_STATE(83)] = 1785,
  [SMALL_STATE(84)] = 1793,
  [SMALL_STATE(85)] = 1801,
  [SMALL_STATE(86)] = 1809,
  [SMALL_STATE(87)] = 1817,
  [SMALL_STATE(88)] = 1825,
  [SMALL_STATE(89)] = 1833,
  [SMALL_STATE(90)] = 1841,
  [SMALL_STATE(91)] = 1849,
  [SMALL_STATE(92)] = 1857,
  [SMALL_STATE(93)] = 1865,
  [SMALL_STATE(94)] = 1873,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2),
  [33] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(38),
  [36] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(46),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(46),
  [42] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(91),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(68),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(61),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(15),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2), SHIFT_REPEAT(18),
  [57] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 2),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(38),
  [64] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(46),
  [67] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(91),
  [70] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(68),
  [73] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(61),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(15),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 2), SHIFT_REPEAT(18),
  [82] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [84] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_command, 1),
  [86] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [88] = {.entry = {.count = 1, .reusable = false}}, SHIFT(53),
  [90] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(91),
  [94] = {.entry = {.count = 1, .reusable = false}}, SHIFT(68),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(61),
  [98] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [108] = {.entry = {.count = 1, .reusable = false}}, SHIFT(52),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [120] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(21),
  [123] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(52),
  [126] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(52),
  [129] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(16),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2),
  [134] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(72),
  [137] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(59),
  [140] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(19),
  [143] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__args_repeat1, 2), SHIFT_REPEAT(39),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [150] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__args, 1),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__args, 2),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__unit, 1),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__unit, 1),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(87),
  [168] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [170] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [172] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_unit_repeat1, 2),
  [174] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_unit_repeat1, 2),
  [176] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_unit_repeat1, 2), SHIFT_REPEAT(56),
  [179] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unit, 2),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 2),
  [183] = {.entry = {.count = 1, .reusable = false}}, SHIFT(56),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unit, 1),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unit, 1),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_func, 2),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_func, 2),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_generics_class, 4, .production_id = 1),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_generics_class, 4, .production_id = 1),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 2),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string, 3),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_block, 3),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_block, 3),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_arg_block, 2),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_arg_block, 2),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 2),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 2),
  [217] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_decorate, 2),
  [219] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_decorate, 2),
  [221] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [223] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_command_repeat1, 1),
  [225] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_command_repeat1, 1),
  [227] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [229] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym__unit, 1), SHIFT(16),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 5),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 5),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 4),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 4),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list, 3),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list, 3),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block, 3),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block, 3),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_operators, 1),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_operators, 1),
  [252] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [254] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_unit_repeat1, 2), SHIFT_REPEAT(57),
  [257] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2),
  [259] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2),
  [261] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym__args_repeat1, 2),
  [263] = {.entry = {.count = 1, .reusable = false}}, SHIFT(79),
  [265] = {.entry = {.count = 1, .reusable = false}}, SHIFT(36),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [269] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2), SHIFT_REPEAT(79),
  [272] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 2),
  [274] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2), SHIFT_REPEAT(60),
  [277] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [281] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [285] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [289] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat1, 2),
  [291] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2), SHIFT_REPEAT(66),
  [294] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [296] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [298] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_string_repeat2, 4),
  [300] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 4),
  [302] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat2, 2),
  [304] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [306] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_unit_repeat1, 2), SHIFT_REPEAT(55),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [321] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [339] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef _WIN32
#define extern __declspec(dllexport)
#endif

extern const TSLanguage *tree_sitter_groovy(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
